// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnswerPrompt(arg1, arg2) {
  return window['go']['ui']['App']['AnswerPrompt'](arg1, arg2);
}

export function ApplyProviderProxySettings(arg1) {
  return window['go']['ui']['App']['ApplyProviderProxySettings'](arg1);
}

export function AutoClassifyAccounts(arg1) {
  return window['go']['ui']['App']['AutoClassifyAccounts'](arg1);
}

export function CancelJob(arg1) {
  return window['go']['ui']['App']['CancelJob'](arg1);
}

export function ClearAccountWorkflow(arg1) {
  return window['go']['ui']['App']['ClearAccountWorkflow'](arg1);
}

export function ClearAccounts(arg1) {
  return window['go']['ui']['App']['ClearAccounts'](arg1);
}

export function ClearPhones(arg1) {
  return window['go']['ui']['App']['ClearPhones'](arg1);
}

export function ConsumePaymentCard() {
  return window['go']['ui']['App']['ConsumePaymentCard']();
}

export function CopyExportPreview(arg1, arg2) {
  return window['go']['ui']['App']['CopyExportPreview'](arg1, arg2);
}

export function CopySessionConversion(arg1) {
  return window['go']['ui']['App']['CopySessionConversion'](arg1);
}

export function CountProxyPoolText(arg1) {
  return window['go']['ui']['App']['CountProxyPoolText'](arg1);
}

export function CreateAccountGroup(arg1) {
  return window['go']['ui']['App']['CreateAccountGroup'](arg1);
}

export function CreateDomainMailAccounts(arg1) {
  return window['go']['ui']['App']['CreateDomainMailAccounts'](arg1);
}

export function CreatePlusAliasAccounts(arg1) {
  return window['go']['ui']['App']['CreatePlusAliasAccounts'](arg1);
}

export function DeleteAccountGroup(arg1, arg2) {
  return window['go']['ui']['App']['DeleteAccountGroup'](arg1, arg2);
}

export function DeleteAccounts(arg1, arg2) {
  return window['go']['ui']['App']['DeleteAccounts'](arg1, arg2);
}

export function Environment() {
  return window['go']['ui']['App']['Environment']();
}

export function ExportMissingRT(arg1) {
  return window['go']['ui']['App']['ExportMissingRT'](arg1);
}

export function ExtractMailboxCode(arg1) {
  return window['go']['ui']['App']['ExtractMailboxCode'](arg1);
}

export function ExtractMailboxInviteLink(arg1) {
  return window['go']['ui']['App']['ExtractMailboxInviteLink'](arg1);
}

export function GenerateLinks(arg1) {
  return window['go']['ui']['App']['GenerateLinks'](arg1);
}

export function GetAccountDetails(arg1) {
  return window['go']['ui']['App']['GetAccountDetails'](arg1);
}

export function GetMailboxMessage(arg1) {
  return window['go']['ui']['App']['GetMailboxMessage'](arg1);
}

export function GetNetworkJobResult(arg1) {
  return window['go']['ui']['App']['GetNetworkJobResult'](arg1);
}

export function ImportAccounts(arg1) {
  return window['go']['ui']['App']['ImportAccounts'](arg1);
}

export function ImportPaymentCards(arg1) {
  return window['go']['ui']['App']['ImportPaymentCards'](arg1);
}

export function ImportPhones(arg1) {
  return window['go']['ui']['App']['ImportPhones'](arg1);
}

export function ListAccounts(arg1) {
  return window['go']['ui']['App']['ListAccounts'](arg1);
}

export function ListJobs() {
  return window['go']['ui']['App']['ListJobs']();
}

export function ListMailboxFolders(arg1) {
  return window['go']['ui']['App']['ListMailboxFolders'](arg1);
}

export function ListMailboxMessages(arg1) {
  return window['go']['ui']['App']['ListMailboxMessages'](arg1);
}

export function ListPaymentCards() {
  return window['go']['ui']['App']['ListPaymentCards']();
}

export function ListPhones() {
  return window['go']['ui']['App']['ListPhones']();
}

export function LoadLogs() {
  return window['go']['ui']['App']['LoadLogs']();
}

export function LoadSettings() {
  return window['go']['ui']['App']['LoadSettings']();
}

export function LoadSummary() {
  return window['go']['ui']['App']['LoadSummary']();
}

export function Log(arg1) {
  return window['go']['ui']['App']['Log'](arg1);
}

export function MergeManualSession(arg1, arg2, arg3) {
  return window['go']['ui']['App']['MergeManualSession'](arg1, arg2, arg3);
}

export function MoveAccountsToGroup(arg1, arg2) {
  return window['go']['ui']['App']['MoveAccountsToGroup'](arg1, arg2);
}

export function OpenAccountFile() {
  return window['go']['ui']['App']['OpenAccountFile']();
}

export function OpenPaymentExtensionDirectory() {
  return window['go']['ui']['App']['OpenPaymentExtensionDirectory']();
}

export function PatchSettings(arg1) {
  return window['go']['ui']['App']['PatchSettings'](arg1);
}

export function PrepareSub2APIExport(arg1) {
  return window['go']['ui']['App']['PrepareSub2APIExport'](arg1);
}

export function PreviewExport(arg1, arg2) {
  return window['go']['ui']['App']['PreviewExport'](arg1, arg2);
}

export function ProviderProxyStatuses() {
  return window['go']['ui']['App']['ProviderProxyStatuses']();
}

export function RenameAccountGroup(arg1, arg2) {
  return window['go']['ui']['App']['RenameAccountGroup'](arg1, arg2);
}

export function ReplaceManualSession(arg1) {
  return window['go']['ui']['App']['ReplaceManualSession'](arg1);
}

export function ReplacePayPalCardHead(arg1, arg2) {
  return window['go']['ui']['App']['ReplacePayPalCardHead'](arg1, arg2);
}

export function ResetPaymentCards() {
  return window['go']['ui']['App']['ResetPaymentCards']();
}

export function ResetPhones() {
  return window['go']['ui']['App']['ResetPhones']();
}

export function SaveExport(arg1, arg2) {
  return window['go']['ui']['App']['SaveExport'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['ui']['App']['SaveSettings'](arg1);
}

export function SaveSub2APIExport(arg1) {
  return window['go']['ui']['App']['SaveSub2APIExport'](arg1);
}

export function SelectLogAccount(arg1) {
  return window['go']['ui']['App']['SelectLogAccount'](arg1);
}

export function SetAccountType(arg1, arg2, arg3) {
  return window['go']['ui']['App']['SetAccountType'](arg1, arg2, arg3);
}

export function StartAcceptWorkspaceInvite(arg1) {
  return window['go']['ui']['App']['StartAcceptWorkspaceInvite'](arg1);
}

export function StartBatchGenerateLinks(arg1) {
  return window['go']['ui']['App']['StartBatchGenerateLinks'](arg1);
}

export function StartBatchRegister(arg1) {
  return window['go']['ui']['App']['StartBatchRegister'](arg1);
}

export function StartBatchRelink(arg1) {
  return window['go']['ui']['App']['StartBatchRelink'](arg1);
}

export function StartCPAExportRefresh(arg1) {
  return window['go']['ui']['App']['StartCPAExportRefresh'](arg1);
}

export function StartCloudMailProbe(arg1) {
  return window['go']['ui']['App']['StartCloudMailProbe'](arg1);
}

export function StartCloudMailTokenGeneration(arg1) {
  return window['go']['ui']['App']['StartCloudMailTokenGeneration'](arg1);
}

export function StartDeactivationScan(arg1) {
  return window['go']['ui']['App']['StartDeactivationScan'](arg1);
}

export function StartDomainRandomRT(arg1) {
  return window['go']['ui']['App']['StartDomainRandomRT'](arg1);
}

export function StartExternalOAuth(arg1) {
  return window['go']['ui']['App']['StartExternalOAuth'](arg1);
}

export function StartK12AcceptAndRefresh(arg1) {
  return window['go']['ui']['App']['StartK12AcceptAndRefresh'](arg1);
}

export function StartK12RegisterAndJoin(arg1) {
  return window['go']['ui']['App']['StartK12RegisterAndJoin'](arg1);
}

export function StartK12RequestInvite(arg1) {
  return window['go']['ui']['App']['StartK12RequestInvite'](arg1);
}

export function StartKeepLogin(arg1) {
  return window['go']['ui']['App']['StartKeepLogin'](arg1);
}

export function StartManualLoginCode(arg1) {
  return window['go']['ui']['App']['StartManualLoginCode'](arg1);
}

export function StartManualPhoneCode(arg1) {
  return window['go']['ui']['App']['StartManualPhoneCode'](arg1);
}

export function StartOAuthAuthorizeRT(arg1) {
  return window['go']['ui']['App']['StartOAuthAuthorizeRT'](arg1);
}

export function StartOpenPaymentWindow(arg1) {
  return window['go']['ui']['App']['StartOpenPaymentWindow'](arg1);
}

export function StartOpenPaymentWindows(arg1) {
  return window['go']['ui']['App']['StartOpenPaymentWindows'](arg1);
}

export function StartOpenSessionReader(arg1) {
  return window['go']['ui']['App']['StartOpenSessionReader'](arg1);
}

export function StartProtocolRegisterSession(arg1) {
  return window['go']['ui']['App']['StartProtocolRegisterSession'](arg1);
}

export function StartProxyPoolCleanup(arg1) {
  return window['go']['ui']['App']['StartProxyPoolCleanup'](arg1);
}

export function StartProxyPoolPrecheck(arg1) {
  return window['go']['ui']['App']['StartProxyPoolPrecheck'](arg1);
}

export function StartRefreshAccountType(arg1) {
  return window['go']['ui']['App']['StartRefreshAccountType'](arg1);
}

export function StartRefreshSession(arg1) {
  return window['go']['ui']['App']['StartRefreshSession'](arg1);
}

export function StartRegister(arg1) {
  return window['go']['ui']['App']['StartRegister'](arg1);
}

export function StartSMSBowerReadTest(arg1) {
  return window['go']['ui']['App']['StartSMSBowerReadTest'](arg1);
}

export function StartSub2APIExport(arg1) {
  return window['go']['ui']['App']['StartSub2APIExport'](arg1);
}

export function StartTeamInvite(arg1) {
  return window['go']['ui']['App']['StartTeamInvite'](arg1);
}

export function StartTeamInviteScanJoin(arg1) {
  return window['go']['ui']['App']['StartTeamInviteScanJoin'](arg1);
}

export function StartTeamLeave(arg1) {
  return window['go']['ui']['App']['StartTeamLeave'](arg1);
}

export function StartTrialEligibility(arg1) {
  return window['go']['ui']['App']['StartTrialEligibility'](arg1);
}

export function StartTurnstileProbe(arg1) {
  return window['go']['ui']['App']['StartTurnstileProbe'](arg1);
}

export function StopAll() {
  return window['go']['ui']['App']['StopAll']();
}

export function StopProviderProxyPools() {
  return window['go']['ui']['App']['StopProviderProxyPools']();
}

export function SwitchPaymentWindowProxy(arg1) {
  return window['go']['ui']['App']['SwitchPaymentWindowProxy'](arg1);
}
