// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ui} from '../models';
import {settings} from '../models';

export function AnswerPrompt(arg1:string,arg2:string):Promise<void>;

export function ApplyProviderProxySettings(arg1:boolean):Promise<Array<ui.ProviderProxyStatusView>>;

export function AutoClassifyAccounts(arg1:ui.AutoClassifyRequest):Promise<ui.AutoClassifyResult>;

export function CancelJob(arg1:string):Promise<void>;

export function ClearAccountWorkflow(arg1:string):Promise<ui.WorkflowClearResult>;

export function ClearAccounts(arg1:boolean):Promise<ui.AccountMutationResult>;

export function ClearPhones(arg1:boolean):Promise<ui.PhonesResult>;

export function ConsumePaymentCard():Promise<ui.PaymentCardConsumeResult>;

export function CopyExportPreview(arg1:string,arg2:Array<string>):Promise<ui.ExportPreview>;

export function CopySessionConversion(arg1:Array<string>):Promise<ui.ExportPreview>;

export function CountProxyPoolText(arg1:string):Promise<number>;

export function CreateAccountGroup(arg1:string):Promise<ui.GroupMutationResult>;

export function CreateDomainMailAccounts(arg1:ui.DomainMailRequest):Promise<ui.GeneratedAccountsResult>;

export function CreatePlusAliasAccounts(arg1:ui.PlusAliasRequest):Promise<ui.GeneratedAccountsResult>;

export function DeleteAccountGroup(arg1:string,arg2:boolean):Promise<ui.GroupMutationResult>;

export function DeleteAccounts(arg1:Array<string>,arg2:boolean):Promise<ui.AccountMutationResult>;

export function Environment():Promise<ui.Env>;

export function ExportMissingRT(arg1:Array<string>):Promise<ui.MissingRTView>;

export function ExtractMailboxCode(arg1:string):Promise<string>;

export function ExtractMailboxInviteLink(arg1:string):Promise<string>;

export function GenerateLinks(arg1:ui.GenerateLinksRequest):Promise<ui.JobView>;

export function GetAccountDetails(arg1:string):Promise<ui.AccountDetails>;

export function GetMailboxMessage(arg1:ui.MailboxMessageRequest):Promise<ui.MailboxMessage>;

export function GetNetworkJobResult(arg1:string):Promise<ui.NetworkJobResult>;

export function ImportAccounts(arg1:string):Promise<ui.ImportResult>;

export function ImportPaymentCards(arg1:string):Promise<ui.PaymentCardsResult>;

export function ImportPhones(arg1:string):Promise<ui.PhonesResult>;

export function ListAccounts(arg1:ui.AccountFilter):Promise<ui.AccountPage>;

export function ListJobs():Promise<Array<ui.JobView>>;

export function ListMailboxFolders(arg1:string):Promise<Array<string>>;

export function ListMailboxMessages(arg1:ui.MailboxMessagesRequest):Promise<Array<ui.MailboxMessage>>;

export function ListPaymentCards():Promise<ui.PaymentCardsResult>;

export function ListPhones():Promise<ui.PhonesResult>;

export function LoadLogs():Promise<ui.LogSnapshot>;

export function LoadSettings():Promise<settings.Settings>;

export function LoadSummary():Promise<ui.StateSummary>;

export function Log(arg1:string):Promise<void>;

export function MergeManualSession(arg1:string,arg2:string,arg3:string):Promise<ui.SessionSaveResult>;

export function MoveAccountsToGroup(arg1:Array<string>,arg2:string):Promise<ui.GroupMutationResult>;

export function OpenAccountFile():Promise<string>;

export function OpenPaymentExtensionDirectory():Promise<string>;

export function PatchSettings(arg1:Record<string, any>):Promise<settings.Settings>;

export function PrepareSub2APIExport(arg1:Array<string>):Promise<ui.Sub2APIPlan>;

export function PreviewExport(arg1:string,arg2:Array<string>):Promise<ui.ExportPreview>;

export function ProviderProxyStatuses():Promise<Array<ui.ProviderProxyStatusView>>;

export function RenameAccountGroup(arg1:string,arg2:string):Promise<ui.GroupMutationResult>;

export function ReplaceManualSession(arg1:string):Promise<ui.SessionSaveResult>;

export function ReplacePayPalCardHead(arg1:string,arg2:ui.PaymentCardView):Promise<string>;

export function ResetPaymentCards():Promise<ui.PaymentCardsResult>;

export function ResetPhones():Promise<ui.PhonesResult>;

export function SaveExport(arg1:string,arg2:Array<string>):Promise<ui.ExportResult>;

export function SaveSettings(arg1:settings.Settings):Promise<void>;

export function SaveSub2APIExport(arg1:string):Promise<ui.Sub2APISaveResult>;

export function SelectLogAccount(arg1:string):Promise<ui.LogSnapshot>;

export function SetAccountType(arg1:Array<string>,arg2:string,arg3:boolean):Promise<ui.AccountMutationResult>;

export function StartAcceptWorkspaceInvite(arg1:ui.WorkspaceInviteRequest):Promise<ui.JobView>;

export function StartBatchGenerateLinks(arg1:ui.StartLinkBatchRequest):Promise<ui.LinkBatchSummary>;

export function StartBatchRegister(arg1:ui.StartBatchRequest):Promise<ui.BatchSummary>;

export function StartBatchRelink(arg1:ui.BatchRelinkRequest):Promise<ui.BatchRelinkSummary>;

export function StartCPAExportRefresh(arg1:Array<string>):Promise<ui.JobView>;

export function StartCloudMailProbe(arg1:ui.CloudMailProbeRequest):Promise<ui.JobView>;

export function StartCloudMailTokenGeneration(arg1:ui.CloudMailTokenRequest):Promise<ui.JobView>;

export function StartDeactivationScan(arg1:ui.DeactivationScanRequest):Promise<ui.JobView>;

export function StartDomainRandomRT(arg1:ui.DomainRandomRTRequest):Promise<ui.DomainRandomRTResult>;

export function StartExternalOAuth(arg1:ui.ExternalOAuthRequest):Promise<ui.JobView>;

export function StartK12AcceptAndRefresh(arg1:ui.K12InviteFlowRequest):Promise<ui.BatchSummary>;

export function StartK12RegisterAndJoin(arg1:ui.K12InviteFlowRequest):Promise<ui.BatchSummary>;

export function StartK12RequestInvite(arg1:ui.K12RequestInviteRequest):Promise<ui.JobView>;

export function StartKeepLogin(arg1:string):Promise<ui.JobView>;

export function StartManualLoginCode(arg1:string):Promise<ui.JobView>;

export function StartManualPhoneCode(arg1:string):Promise<ui.JobView>;

export function StartOAuthAuthorizeRT(arg1:ui.AuthBatchRequest):Promise<ui.BatchSummary>;

export function StartOpenPaymentWindow(arg1:ui.OpenPaymentWindowRequest):Promise<ui.JobView>;

export function StartOpenPaymentWindows(arg1:ui.OpenPaymentWindowsRequest):Promise<ui.OpenPaymentWindowsResult>;

export function StartOpenSessionReader(arg1:string):Promise<ui.JobView>;

export function StartProtocolRegisterSession(arg1:ui.AuthBatchRequest):Promise<ui.BatchSummary>;

export function StartProxyPoolCleanup(arg1:ui.ProxyPoolOperationRequest):Promise<ui.JobView>;

export function StartProxyPoolPrecheck(arg1:ui.ProxyPoolOperationRequest):Promise<ui.JobView>;

export function StartRefreshAccountType(arg1:ui.RefreshAccountTypeRequest):Promise<ui.JobView>;

export function StartRefreshSession(arg1:ui.SessionRefreshRequest):Promise<ui.JobView>;

export function StartRegister(arg1:ui.StartRegisterRequest):Promise<ui.JobView>;

export function StartSMSBowerReadTest(arg1:ui.SMSBowerReadRequest):Promise<ui.JobView>;

export function StartSub2APIExport(arg1:Array<string>):Promise<ui.JobView>;

export function StartTeamInvite(arg1:ui.TeamInviteRequest):Promise<ui.JobView>;

export function StartTeamInviteScanJoin(arg1:ui.TeamInviteScanJoinRequest):Promise<ui.BatchSummary>;

export function StartTeamLeave(arg1:ui.TeamLeaveRequest):Promise<ui.JobView>;

export function StartTrialEligibility(arg1:ui.TrialEligibilityRequest):Promise<ui.JobView>;

export function StartTurnstileProbe(arg1:ui.TurnstileProbeRequest):Promise<ui.JobView>;

export function StopAll():Promise<void>;

export function StopProviderProxyPools():Promise<Array<ui.ProviderProxyStatusView>>;

export function SwitchPaymentWindowProxy(arg1:string):Promise<ui.PaymentProxySwitchResult>;
