// Ports of the Python value semantics (truthiness, str(), str.strip(), int(),
// str.isdigit(), str.casefold(), re.split(r"\s+", ...)) that app.py's derived
// -status logic leans on. The lookup maps hold raw encoding/json values (any),
// the same shape Python sees after json.load, so every conversion below must
// follow Python rules, not Go ones.
package accounts

import (
	"encoding/json"
	"math"
	"regexp"
	"strconv"
	"strings"
	"unicode"
)

// pyFalsy reports whether Python would treat v as falsy in an `or` chain.
// Note this is NOT strings.TrimSpace(...)==""; Python's `or` does not strip —
// " " is truthy while "" is falsy (app.py:19058/19062/19063 rely on this).
func pyFalsy(v any) bool {
	switch t := v.(type) {
	case nil:
		return true
	case string:
		return t == ""
	case bool:
		return !t
	case float64:
		return t == 0
	case int:
		return t == 0
	case int64:
		return t == 0
	case json.Number:
		f, err := t.Float64()
		return err == nil && f == 0
	case map[string]any:
		return len(t) == 0
	case []any:
		return len(t) == 0
	}
	return false
}

// pyStr mirrors str(v) for JSON-decoded values. json.Unmarshal yields float64
// for every JSON number while Python's json keeps int and float distinct; the
// Python side only ever stores these fields as int or str (app.py:14034/14038,
// 18665), so integral floats are formatted without ".0" to match str(int).
// For dict/list only truthiness-after-strip of the result matters at our call
// sites, so a stable non-empty stand-in replaces Python's repr.
func pyStr(v any) string {
	switch t := v.(type) {
	case nil:
		return "None"
	case string:
		return t
	case bool:
		if t {
			return "True"
		}
		return "False"
	case json.Number:
		return t.String()
	case float64:
		if t == math.Trunc(t) && math.Abs(t) < 1e15 {
			return strconv.FormatInt(int64(t), 10)
		}
		return strconv.FormatFloat(t, 'g', -1, 64)
	case int:
		return strconv.Itoa(t)
	case int64:
		return strconv.FormatInt(t, 10)
	case map[string]any:
		return "{...}"
	case []any:
		return "[...]"
	}
	return "?"
}

// pyStrOr mirrors the ubiquitous str(v or "") idiom (app.py:19058 etc.).
func pyStrOr(v any) string {
	if pyFalsy(v) {
		return ""
	}
	return pyStr(v)
}

// orChain mirrors `a or b or ...`: the first truthy operand, nil when none is.
func orChain(vals ...any) any {
	for _, v := range vals {
		if !pyFalsy(v) {
			return v
		}
	}
	return nil
}

// pyIsSpace mirrors Python's str.isspace() for one rune: Go's unicode.IsSpace
// plus the C0 information separators U+001C..U+001F, which Python counts as
// whitespace and Go does not. Both agree on NBSP U+00A0, NEL U+0085 and Z*.
func pyIsSpace(r rune) bool {
	return unicode.IsSpace(r) || (r >= 0x1c && r <= 0x1f)
}

// pyStrip mirrors str.strip(). (Known port trap: rendered text carries NBSP,
// and Python strips it here — strings.TrimSpace happens to agree on NBSP but
// not on U+001C-1F.)
func pyStrip(s string) string {
	return strings.TrimFunc(s, pyIsSpace)
}

// reWhitespace is the Go equivalent of Python's `\s+` for str patterns
// (app.py:19116). Python's `\s` matches exactly str.isspace(); Go's RE2 `\s`
// is the ASCII class [\t\n\f\r ] and omits even \v, so \v, U+001C..U+001F,
// U+0085 and all of \p{Z} (NBSP, ideographic space U+3000, ...) are added back
// explicitly. Rendered Chinese UI text routinely carries U+00A0 and U+3000.
var reWhitespace = regexp.MustCompile(`[\s\x{000B}\x{001C}-\x{001F}\x{0085}\p{Z}]+`)

// pyFoldExtra is every code point whose Python str.casefold() differs from Go's
// unicode.ToLower, minus the Cherokee blocks (cherokeeFold below). Go has no
// full case folding in the standard library and golang.org/x/text is only an
// indirect dependency, so the table is spelled out; it was GENERATED by walking
// all 0x110000 code points under CPython 3.12 / Unicode 15.0.0, not hand-picked.
// Do not prune it "because the app only sees ASCII": the search box and the
// group names are free text, and TestCaseFoldExactVsPython pins the whole table.
var pyFoldExtra = map[rune]string{
	0x00B5: "μ", 0x00DF: "ss", 0x0130: "i̇", 0x0149: "ʼn",
	0x017F: "s", 0x01F0: "ǰ", 0x0345: "ι", 0x0390: "ΐ",
	0x03B0: "ΰ", 0x03C2: "σ", 0x03D0: "β", 0x03D1: "θ",
	0x03D5: "φ", 0x03D6: "π", 0x03F0: "κ", 0x03F1: "ρ",
	0x03F5: "ε", 0x0587: "եւ", 0x1C80: "в", 0x1C81: "д",
	0x1C82: "о", 0x1C83: "с", 0x1C84: "т", 0x1C85: "т",
	0x1C86: "ъ", 0x1C87: "ѣ", 0x1C88: "ꙋ", 0x1E96: "ẖ",
	0x1E97: "ẗ", 0x1E98: "ẘ", 0x1E99: "ẙ", 0x1E9A: "aʾ",
	0x1E9B: "ṡ", 0x1E9E: "ss", 0x1F50: "ὐ", 0x1F52: "ὒ",
	0x1F54: "ὔ", 0x1F56: "ὖ", 0x1F80: "ἀι", 0x1F81: "ἁι",
	0x1F82: "ἂι", 0x1F83: "ἃι", 0x1F84: "ἄι", 0x1F85: "ἅι",
	0x1F86: "ἆι", 0x1F87: "ἇι", 0x1F88: "ἀι", 0x1F89: "ἁι",
	0x1F8A: "ἂι", 0x1F8B: "ἃι", 0x1F8C: "ἄι", 0x1F8D: "ἅι",
	0x1F8E: "ἆι", 0x1F8F: "ἇι", 0x1F90: "ἠι", 0x1F91: "ἡι",
	0x1F92: "ἢι", 0x1F93: "ἣι", 0x1F94: "ἤι", 0x1F95: "ἥι",
	0x1F96: "ἦι", 0x1F97: "ἧι", 0x1F98: "ἠι", 0x1F99: "ἡι",
	0x1F9A: "ἢι", 0x1F9B: "ἣι", 0x1F9C: "ἤι", 0x1F9D: "ἥι",
	0x1F9E: "ἦι", 0x1F9F: "ἧι", 0x1FA0: "ὠι", 0x1FA1: "ὡι",
	0x1FA2: "ὢι", 0x1FA3: "ὣι", 0x1FA4: "ὤι", 0x1FA5: "ὥι",
	0x1FA6: "ὦι", 0x1FA7: "ὧι", 0x1FA8: "ὠι", 0x1FA9: "ὡι",
	0x1FAA: "ὢι", 0x1FAB: "ὣι", 0x1FAC: "ὤι", 0x1FAD: "ὥι",
	0x1FAE: "ὦι", 0x1FAF: "ὧι", 0x1FB2: "ὰι", 0x1FB3: "αι",
	0x1FB4: "άι", 0x1FB6: "ᾶ", 0x1FB7: "ᾶι", 0x1FBC: "αι",
	0x1FBE: "ι", 0x1FC2: "ὴι", 0x1FC3: "ηι", 0x1FC4: "ήι",
	0x1FC6: "ῆ", 0x1FC7: "ῆι", 0x1FCC: "ηι", 0x1FD2: "ῒ",
	0x1FD3: "ΐ", 0x1FD6: "ῖ", 0x1FD7: "ῗ", 0x1FE2: "ῢ",
	0x1FE3: "ΰ", 0x1FE4: "ῤ", 0x1FE6: "ῦ", 0x1FE7: "ῧ",
	0x1FF2: "ὼι", 0x1FF3: "ωι", 0x1FF4: "ώι", 0x1FF6: "ῶ",
	0x1FF7: "ῶι", 0x1FFC: "ωι", 0xFB00: "ff", 0xFB01: "fi",
	0xFB02: "fl", 0xFB03: "ffi", 0xFB04: "ffl", 0xFB05: "st",
	0xFB06: "st", 0xFB13: "մն", 0xFB14: "մե", 0xFB15: "մի",
	0xFB16: "վն", 0xFB17: "մխ",
}

// cherokeeFold is the one script that case-folds UPWARDS: CaseFolding.txt maps
// the lowercase syllables U+AB70..U+ABBF and U+13F8..U+13FD onto the historic
// uppercase ones, and leaves U+13A0..U+13F5 alone. unicode.ToLower does the
// opposite in every one of those 172 code points, which is why they cannot go
// through the ToLower fast path. Kept as ranges rather than 172 table rows.
func cherokeeFold(r rune) (rune, bool) {
	switch {
	case r >= 0x13A0 && r <= 0x13F5:
		return r, true // already the folded form
	case r >= 0x13F8 && r <= 0x13FD:
		return r - 8, true
	case r >= 0xAB70 && r <= 0xABBF:
		return r - 0x97D0, true
	}
	return 0, false
}

func needsFullFold(r rune) bool {
	if r < 0xB5 { // ASCII and the C1 block never differ
		return false
	}
	if _, ok := pyFoldExtra[r]; ok {
		return true
	}
	_, ok := cherokeeFold(r)
	return ok
}

// caseFold mirrors str.casefold() (app.py:19101/19103/19106/19116/19130/19143).
// The common case (ASCII address, CJK status) never touches the table.
func caseFold(s string) string {
	if !strings.ContainsFunc(s, needsFullFold) {
		return strings.ToLower(s)
	}
	var b strings.Builder
	b.Grow(len(s))
	for _, r := range s {
		if mapped, ok := pyFoldExtra[r]; ok {
			b.WriteString(mapped)
			continue
		}
		if folded, ok := cherokeeFold(r); ok {
			b.WriteRune(folded)
			continue
		}
		b.WriteRune(unicode.ToLower(r))
	}
	return b.String()
}

// pyLower mirrors str.lower() (app.py:19025/19082/19750). U+0130 is the only
// code point whose full lowercase mapping is longer than one rune, and
// strings.ToLower collapses it to a bare "i" — which would merge the row
// identities of "İ@x.com" and "i@x.com" (Key is what a selection set holds).
//
// DIVERGENCE: str.lower() also applies the context-sensitive Final_Sigma rule
// ("ΟΔΟΣ".lower() == "οδος", ours gives "οδοσ"). Reproducing it needs the Cased
// and Case_Ignorable derived properties, which Go does not export. Nothing
// compares one of these strings against a Python-produced one — Key, the group
// picker and the plan-type test all fold both sides in Go — so no outcome
// differs; see TestPyLowerFinalSigmaDivergence. The same call is spelled the
// same way in internal/opll and internal/logs.
func pyLower(s string) string {
	if strings.ContainsRune(s, 'İ') {
		s = strings.ReplaceAll(s, "İ", "i̇")
	}
	return strings.ToLower(s)
}

// ndDigitValue returns the decimal value of an Nd rune, i.e. Python's
// int(chr(cp)) for a single decimal digit.
//
// Unicode requires every Nd character to belong to a set of ten consecutive
// codepoints starting at that script's zero, so the value is the offset from
// the start of the run — but adjacent runs are NOT separated by a gap. The
// five Mathematical digit blocks U+1D7CE..U+1D7FF are one unbroken span of 50
// digits, and a naive "walk down at most nine places until the previous rune
// is not a digit" answers 9 for all 40 codepoints after the first block
// (int("𝟢") is 0, not 9 — that bug made HasK12Success reject a 2xx written in
// mathematical digits). Walk to the start of the WHOLE contiguous span, which
// is always a zero and always a multiple of ten long, then take the offset
// modulo ten.
func ndDigitValue(r rune) (int, bool) {
	if !unicode.IsDigit(r) {
		return 0, false
	}
	if r <= '9' {
		return int(r - '0'), true
	}
	start := r
	for start > 0 && unicode.IsDigit(start-1) {
		start--
	}
	return int(r-start) % 10, true
}

// pyDigitInt mirrors `s.isdigit() and int(s)` (app.py:19073-19075): every rune
// must be a decimal digit, then the string converts as a non-negative int.
//
// Two deliberate narrowings of Python:
//   - Python's str.isdigit() is also true for Numeric_Type=Digit characters
//     outside Nd (superscripts such as "²"), and int() then raises ValueError
//     on them — a live crash path. Go's unicode.IsDigit is Nd-only, so this
//     returns ok=false there instead of panicking. (Verified against CPython:
//     the code points int() accepts as a lone digit are EXACTLY Nd.)
//   - Python ints are arbitrary precision, Go's are 64-bit, so an absurdly long
//     digit string SATURATES at math.MaxInt instead of wrapping. It used to stop
//     accumulating past 1e9, which silently answered 1234567890 for
//     int("12345678901234") — wrong for AttemptCount, which does display the
//     number. Saturation cannot change HasK12Success: anything that overflows is
//     far above 300.
func pyDigitInt(s string) (int, bool) {
	if s == "" {
		return 0, false
	}
	value := 0
	saturated := false
	for _, r := range s {
		d, ok := ndDigitValue(r)
		if !ok {
			return 0, false
		}
		if saturated {
			continue
		}
		if value > (math.MaxInt-d)/10 {
			value, saturated = math.MaxInt, true
			continue
		}
		value = value*10 + d
	}
	return value, true
}

// pyIntStrip is the padding int() itself tolerates, which is NOT str.strip()'s
// set: verified against CPython over all 1,112,064 code points, int() accepts
// every str.isspace() character EXCEPT the C0 information separators
// U+001C..U+001F. That set is exactly Go's unicode.IsSpace, i.e. TrimSpace —
// pyStrip would be wrong here, and would make Go answer 8 for "\x1c8\x1f" where
// CPython raises ValueError (which pyInt reports as 0, see below).
func pyIntStrip(s string) string { return strings.TrimSpace(s) }

// pyIntDigits mirrors the digit grammar of int(str): decimal digits with single
// underscores BETWEEN digits ("1_0" is 10, "_1", "1_" and "1__0" all raise).
// Python allows the separator with non-ASCII digits too — int("٩_٩") is 99.
func pyIntDigits(s string) (int, bool) {
	if s == "" {
		return 0, false
	}
	cleaned := s
	if strings.ContainsRune(s, '_') {
		var b strings.Builder
		b.Grow(len(s))
		prevDigit := false
		runes := []rune(s)
		for i, r := range runes {
			if r == '_' {
				if !prevDigit || i+1 >= len(runes) || !unicode.IsDigit(runes[i+1]) {
					return 0, false
				}
				prevDigit = false
				continue
			}
			b.WriteRune(r)
			prevDigit = unicode.IsDigit(r)
		}
		cleaned = b.String()
	}
	return pyDigitInt(cleaned)
}

// pyInt mirrors int(v) for JSON-decoded values (app.py:19093's
// `max(0, int(... or 0))`). Python truncates floats toward zero and accepts a
// surrounding-whitespace-padded decimal string. Where Python would raise
// (TypeError/ValueError on a dict, list or non-numeric string) this returns 0:
// app.py has no handler there, so raising would only crash the render pass.
func pyInt(v any) int {
	switch t := v.(type) {
	case nil:
		return 0
	case bool:
		if t {
			return 1
		}
		return 0
	case int:
		return t
	case int64:
		return int(t)
	case float64:
		if math.IsNaN(t) || math.IsInf(t, 0) {
			return 0
		}
		return int(math.Trunc(t))
	case json.Number:
		if n, err := t.Int64(); err == nil {
			return int(n)
		}
		if f, err := t.Float64(); err == nil {
			return int(math.Trunc(f))
		}
		return 0
	case string:
		s := pyIntStrip(t)
		neg := false
		if strings.HasPrefix(s, "+") || strings.HasPrefix(s, "-") {
			neg = s[0] == '-'
			s = s[1:]
		}
		n, ok := pyIntDigits(s)
		if !ok {
			return 0
		}
		if neg {
			return -n
		}
		return n
	}
	return 0
}
