package mail

// pytext.go holds the `re` and `str` equivalences this package needs to
// reproduce CPython on MAIL text. Same idea (and the same three character
// classes) as internal/worker/pytext.go; duplicated on purpose so the mail port
// stays a leaf that does not import the worker.
//
// Mail bodies are the worst possible input for Go's ASCII-only defaults:
// html_to_text unescapes `&nbsp;` LAST (app.py:6283), so every rendered HTML
// mail hands the classifiers U+00A0 where Python's `\s` sees whitespace and
// RE2's does not. The three equivalences below were established by comparing
// CPython against Go over U+0000..U+10FFFF:
//
//	Python str-mode `\s`  ==  Go [\s\x{000B}\x{001C}-\x{001F}\x{0085}\p{Z}]
//	Python str-mode `\w`  ==  Go [\p{L}\p{N}_]
//	Python str-mode `\d`  ==  Go \p{Nd}
//
// Concrete defects this file removes, each reproduced against app.py:
//   - "account&nbsp;has&nbsp;been&nbsp;deactivated": Python collapses the NBSPs
//     and matches the ban marker; ASCII `\s+` left them and the ban was missed.
//   - an OTP written in fullwidth or Arabic-Indic digits: Python's `\d{6}`
//     matches, `[0-9]{6}` does not, and the code came back "".
//   - a Chinese subject "中文deactivated": Python's `\b` sees NO boundary between
//     文 and d (both are `\w`), RE2's ASCII `\b` does, so Go flagged a ban that
//     Python did not.

import (
	"fmt"
	"math"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"time"
	"unicode"
	"unicode/utf8"
)

// pyWSClass is the BODY of a character class equal to Python's str-mode `\s`.
const pyWSClass = `\s\x{000B}\x{001C}-\x{001F}\x{0085}\p{Z}`

// pyWS is one Python-`\s` character, ready to embed in a pattern.
const pyWS = `[` + pyWSClass + `]`

// pyDigit is the BODY of a character class equal to Python's str-mode `\d`
// (category Nd, 680 code points); pyNonDigit is Python's `[^\d]`.
const (
	pyDigit    = `\p{Nd}`
	pyNonDigit = `[^` + pyDigit + `]`
)

// pyWordChar is the BODY of a character class equal to Python's str-mode `\w`;
// pyNonWord is one non-`\w` character.
const (
	pyWordChar = `\p{L}\p{N}_`
	pyNonWord  = `[^` + pyWordChar + `]`
)

// pyB wraps a pattern in Python-compatible (Unicode-aware) word boundaries,
// standing in for `\b(...)\b`.
//
// RE2 has no lookaround, so the boundary characters are CONSUMED. Every call
// site below is either a boolean MatchString or takes only the FIRST match, and
// consuming one leading delimiter shifts every candidate start position by the
// same single character, so the leftmost match — and therefore the captured
// group — is unchanged. Do NOT reuse this for FindAll: two adjacent matches
// that share a delimiter would collapse into one.
func pyB(inner string) string {
	return `(?:^|` + pyNonWord + `)(?:` + inner + `)(?:$|` + pyNonWord + `)`
}

// pyIsSpace is str.isspace() for one character. unicode.IsSpace covers 25 of
// the 29 code points and omits the four information separators U+001C..U+001F,
// which str.strip() does remove.
func pyIsSpace(r rune) bool {
	return unicode.IsSpace(r) || (r >= 0x1c && r <= 0x1f)
}

// pyStrip is str.strip(); pyRStrip is str.rstrip().
func pyStrip(s string) string  { return strings.TrimFunc(s, pyIsSpace) }
func pyRStrip(s string) string { return strings.TrimRightFunc(s, pyIsSpace) }

// pyLower is str.lower(). Full lowercase mapping differs from Go's simple
// mapping at exactly ONE code point, U+0130 LATIN CAPITAL LETTER I WITH DOT
// ABOVE, which lowercases to two runes (i + U+0307); verified by walking
// U+0000..U+10FFFF.
//
// DIVERGENCE: CPython also applies the Greek final-sigma context rule, so
// "ΟΔΟΣ".lower() is "οδος" while this returns "οδοσ". Reproducing it needs the
// Cased/Case_Ignorable properties Go does not export, and no call site here
// lowercases Greek prose — the inputs are URLs and ASCII marker words.
func pyLower(s string) string {
	if strings.ContainsRune(s, 'İ') {
		s = strings.ReplaceAll(s, "İ", "i̇")
	}
	return strings.ToLower(s)
}

// pyFoldPairs is every code point whose str.casefold() differs from Go's
// strings.ToLower, EXCEPT the Cherokee block (a pure range rule, see
// pyFoldCherokee). Generated by walking U+0000..U+10FFFF in CPython 3.12
// (Unicode 15.0.0) and diffing against strings.ToLower; encoded as
// space-separated "<rune><replacement>" records, none of which contains a
// space. 132 records.
const pyFoldPairs = "µμ ßss İi̇ ŉʼn ſs ǰǰ ͅι " +
	"ΐΐ ΰΰ ςσ ϐβ ϑθ " +
	"ϕφ ϖπ ϰκ ϱρ ϵε ևեւ " +
	"ᏸᏰ ᏹᏱ ᏺᏲ ᏻᏳ ᏼᏴ ᏽᏵ ᲀв " +
	"ᲁд ᲂо ᲃс ᲄт ᲅт ᲆъ ᲇѣ " +
	"ᲈꙋ ẖẖ ẗẗ ẘẘ ẙẙ ẚaʾ " +
	"ẛṡ ẞss ὐὐ ὒὒ ὔὔ " +
	"ὖὖ ᾀἀι ᾁἁι ᾂἂι " +
	"ᾃἃι ᾄἄι ᾅἅι ᾆἆι " +
	"ᾇἇι ᾈἀι ᾉἁι ᾊἂι " +
	"ᾋἃι ᾌἄι ᾍἅι ᾎἆι " +
	"ᾏἇι ᾐἠι ᾑἡι ᾒἢι " +
	"ᾓἣι ᾔἤι ᾕἥι ᾖἦι " +
	"ᾗἧι ᾘἠι ᾙἡι ᾚἢι " +
	"ᾛἣι ᾜἤι ᾝἥι ᾞἦι " +
	"ᾟἧι ᾠὠι ᾡὡι ᾢὢι " +
	"ᾣὣι ᾤὤι ᾥὥι ᾦὦι " +
	"ᾧὧι ᾨὠι ᾩὡι ᾪὢι " +
	"ᾫὣι ᾬὤι ᾭὥι ᾮὦι " +
	"ᾯὧι ᾲὰι ᾳαι ᾴάι " +
	"ᾶᾶ ᾷᾶι ᾼαι ιι " +
	"ῂὴι ῃηι ῄήι ῆῆ " +
	"ῇῆι ῌηι ῒῒ " +
	"ΐΐ ῖῖ ῗῗ " +
	"ῢῢ ΰΰ ῤῤ ῦῦ " +
	"ῧῧ ῲὼι ῳωι ῴώι " +
	"ῶῶ ῷῶι ῼωι ﬀff ﬁfi ﬂfl " +
	"ﬃffi ﬄffl ﬅst ﬆst ﬓմն ﬔմե " +
	"ﬕմի ﬖվն ﬗմխ"

var pyFoldMap = buildPyFoldMap()

func buildPyFoldMap() map[rune]string {
	out := make(map[rune]string, 132)
	for _, record := range strings.Split(pyFoldPairs, " ") {
		if record == "" {
			continue
		}
		key, size := utf8.DecodeRuneInString(record)
		out[key] = record[size:]
	}
	return out
}

// pyFoldCherokee is the Cherokee half of the casefold table, which folds to
// UPPERCASE rather than lowercase: the syllabary's lowercase letters were added
// to Unicode long after the uppercase ones, so CaseFolding.txt keeps the old
// (uppercase) form as the fold target. Go's strings.ToLower goes the other way.
func pyFoldCherokee(r rune) (rune, bool) {
	switch {
	case r >= 0x13A0 && r <= 0x13F5:
		return r, true
	case r >= 0xAB70 && r <= 0xABBF:
		return r - 0xAB70 + 0x13A0, true
	}
	return 0, false
}

// pyCaseFold is str.casefold(): FULL Unicode case folding, which the Go
// standard library does not provide. ß folds to "ss" and ſ to "s", so casefold
// is NOT strings.ToLower — every deactivation / security marker in this file is
// compared against a folded haystack, and "found as compromiſed" is a match in
// Python.
func pyCaseFold(s string) string {
	if isASCII(s) {
		return strings.ToLower(s)
	}
	var b strings.Builder
	b.Grow(len(s))
	for _, r := range s {
		if v, ok := pyFoldMap[r]; ok {
			b.WriteString(v)
			continue
		}
		if v, ok := pyFoldCherokee(r); ok {
			b.WriteRune(v)
			continue
		}
		b.WriteRune(unicode.ToLower(r))
	}
	return b.String()
}

// pyDigitValue is Python's int(ch) for one character: the decimal value of a
// Unicode digit, or (0, false) outside category Nd.
//
// Nd is laid out as complete, aligned runs of ten, so the offset from the start
// of the containing range modulo ten IS the value. Several ranges hold more
// than one run (U+1D7CE..U+1D7FF is five), which is why walking backwards to
// the nearest non-Nd rune would answer 9 for U+1D7D8 MATHEMATICAL DOUBLE-STRUCK
// DIGIT ZERO.
func pyDigitValue(r rune) (int, bool) {
	if r <= unicode.MaxLatin1 {
		if r >= '0' && r <= '9' {
			return int(r - '0'), true
		}
		return 0, false
	}
	for _, rg := range unicode.Nd.R16 {
		if rune(rg.Lo) <= r && r <= rune(rg.Hi) && rg.Stride == 1 {
			return int((r - rune(rg.Lo)) % 10), true
		}
	}
	for _, rg := range unicode.Nd.R32 {
		if rune(rg.Lo) <= r && r <= rune(rg.Hi) && rg.Stride == 1 {
			return int((r - rune(rg.Lo)) % 10), true
		}
	}
	return 0, false
}

// pyDatetimeTimestamp is datetime.timestamp(), which returns a FLOAT carrying
// microseconds — CPython computes ((delta_days*86400 + delta_seconds)*10**6 +
// microseconds) / 10**6, so UnixMicro()/1e6 is the same double.
// time.Time.Unix() truncates to whole seconds, which backdated a Cloud Mail
// message by up to a second and could push it under the caller's min_timestamp.
func pyDatetimeTimestamp(t time.Time) float64 {
	return float64(t.UnixMicro()) / 1e6
}

// pyFloat is Python's float(s) restricted to the shape its one caller has
// already fullmatched: `\d+(?:\.\d+)?` over Python's `\d`, i.e. Nd digits.
// CPython's float() accepts a fullwidth or Arabic-Indic spelling and
// strconv.ParseFloat does not, so the digits are folded to ASCII first.
func pyFloat(s string) float64 {
	var b strings.Builder
	b.Grow(len(s))
	for _, r := range s {
		if v, ok := pyDigitValue(r); ok {
			b.WriteByte(byte('0' + v))
			continue
		}
		b.WriteRune(r)
	}
	// A ParseFloat range error still yields ±Inf, which is what float() returns
	// for an overlong digit run, so the error is deliberately dropped.
	f, _ := strconv.ParseFloat(b.String(), 64)
	return f
}

func isASCII(s string) bool {
	for i := 0; i < len(s); i++ {
		if s[i] >= utf8.RuneSelf {
			return false
		}
	}
	return true
}

// ---------------------------------------------------------------------------
// Python value semantics over json.loads output
// ---------------------------------------------------------------------------

// pyTruthy is Python's bool(v) for the shapes json.Unmarshal produces: None,
// False, 0, "", [] and {} are falsy, everything else is truthy.
func pyTruthy(v interface{}) bool {
	switch t := v.(type) {
	case nil:
		return false
	case bool:
		return t
	case string:
		return t != ""
	case float64:
		return t != 0
	case []interface{}:
		return len(t) != 0
	case map[string]interface{}:
		return len(t) != 0
	}
	return true
}

// pyOr is Python's `a or b or c`: the first truthy operand, else the last one.
// Truthiness is tested on the RAW value, before any str()/strip().
func pyOr(values ...interface{}) interface{} {
	for i, v := range values {
		if pyTruthy(v) || i == len(values)-1 {
			return v
		}
	}
	return nil
}

// pyStr is Python's str(v) over json.loads output. A JWT `aud` claim is
// routinely an ARRAY, and Python renders that as "['https://…']" — brackets,
// quotes and ", " separators — which is what lands in the operator-facing log
// line. fmt's "%v" would print "[https://…]".
func pyStr(v interface{}) string {
	switch t := v.(type) {
	case nil:
		return "None"
	case string:
		return t
	case bool:
		if t {
			return "True"
		}
		return "False"
	case float64:
		// CPython's json.loads yields an int for an integral JSON number, so
		// str() prints no ".0" and never an exponent.
		if t == math.Trunc(t) && math.Abs(t) < 1e16 {
			return strconv.FormatInt(int64(t), 10)
		}
		return strconv.FormatFloat(t, 'g', -1, 64)
	case []interface{}:
		parts := make([]string, 0, len(t))
		for _, item := range t {
			parts = append(parts, pyRepr(item))
		}
		return "[" + strings.Join(parts, ", ") + "]"
	case map[string]interface{}:
		// Go maps have no order; CPython dicts do. Unreachable for `aud`/`scp`
		// (never objects in a Microsoft token) and only ever a log string.
		keys := make([]string, 0, len(t))
		for k := range t {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		parts := make([]string, 0, len(keys))
		for _, k := range keys {
			parts = append(parts, pyRepr(k)+": "+pyRepr(t[k]))
		}
		return "{" + strings.Join(parts, ", ") + "}"
	}
	return fmt.Sprintf("%v", v)
}

// pyRepr is Python's repr(v) — the form str() uses for items INSIDE a
// container. Only strings differ from str(): they gain quotes.
func pyRepr(v interface{}) string {
	s, ok := v.(string)
	if !ok {
		return pyStr(v)
	}
	quote := "'"
	if strings.Contains(s, "'") && !strings.Contains(s, `"`) {
		quote = `"`
	}
	var b strings.Builder
	b.WriteString(quote)
	for _, r := range s {
		switch {
		case r == '\\':
			b.WriteString(`\\`)
		case string(r) == quote:
			b.WriteString(`\` + quote)
		case r == '\n':
			b.WriteString(`\n`)
		case r == '\r':
			b.WriteString(`\r`)
		case r == '\t':
			b.WriteString(`\t`)
		default:
			b.WriteRune(r)
		}
	}
	b.WriteString(quote)
	return b.String()
}

// ---------------------------------------------------------------------------
// urlsplit / unquote
//
// Duplicated from internal/opll and internal/worker on purpose (both are
// heavier packages this leaf must not import). See isChatGPTTeamInviteURL for
// the two invites net/url dropped that urllib keeps.
// ---------------------------------------------------------------------------

// pySplitResult is urllib.parse.SplitResult. Path/Query are RAW — urlsplit
// never percent-decodes, while url.URL.Path is already decoded.
type pySplitResult struct {
	Scheme   string
	Netloc   string
	Path     string
	Query    string
	Fragment string
}

var pySchemeCharRe = regexp.MustCompile(`^[A-Za-z][A-Za-z0-9+.\-]*$`)

// pyC0AndSpace is WHATWG "C0 control or space" — U+0000..U+0020.
const pyC0AndSpace = "\x00\x01\x02\x03\x04\x05\x06\a\b\t\n\v\f\r\x0e\x0f" +
	"\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f "

var pyURLUnsafeStripper = strings.NewReplacer("\t", "", "\n", "", "\r", "")

// pyURLSplit mirrors urllib.parse.urlsplit(), which never fails.
func pyURLSplit(value string) pySplitResult {
	// CPython: lstrip C0-control-or-space, then delete every tab/CR/LF.
	rest := pyURLUnsafeStripper.Replace(strings.TrimLeft(value, pyC0AndSpace))
	var out pySplitResult
	if i := strings.IndexByte(rest, ':'); i > 0 && pySchemeCharRe.MatchString(rest[:i]) {
		out.Scheme = pyLower(rest[:i])
		rest = rest[i+1:]
	}
	if strings.HasPrefix(rest, "//") {
		body := rest[2:]
		end := len(body)
		for _, c := range []byte{'/', '?', '#'} {
			if j := strings.IndexByte(body, c); j >= 0 && j < end {
				end = j
			}
		}
		out.Netloc, rest = body[:end], body[end:]
	}
	if i := strings.IndexByte(rest, '#'); i >= 0 {
		rest, out.Fragment = rest[:i], rest[i+1:]
	}
	if i := strings.IndexByte(rest, '?'); i >= 0 {
		rest, out.Query = rest[:i], rest[i+1:]
	}
	out.Path = rest
	return out
}

// Hostname mirrors SplitResult.hostname: netloc minus userinfo and port,
// lowercased ("" where Python returns None).
func (s pySplitResult) Hostname() string {
	host := s.Netloc
	if i := strings.LastIndexByte(host, '@'); i >= 0 {
		host = host[i+1:]
	}
	if strings.Contains(host, "[") && strings.Contains(host, "]") {
		host = host[strings.Index(host, "[")+1:]
		if j := strings.Index(host, "]"); j >= 0 {
			host = host[:j]
		}
	} else if i := strings.IndexByte(host, ':'); i >= 0 {
		host = host[:i]
	}
	return pyLower(host)
}

// pyUnquote is urllib.parse.unquote(s) with its defaults (encoding="utf-8",
// errors="replace"): every well-formed %XX is decoded, a malformed one is kept
// verbatim, '+' is left ALONE (that is unquote_plus, which url.QueryUnescape
// does), and undecodable bytes become U+FFFD.
func pyUnquote(value string) string {
	if !strings.Contains(value, "%") {
		return value
	}
	out := make([]byte, 0, len(value))
	for i := 0; i < len(value); i++ {
		if value[i] == '%' && i+2 < len(value) {
			hi, okHi := pyUnhex(value[i+1])
			lo, okLo := pyUnhex(value[i+2])
			if okHi && okLo {
				out = append(out, hi<<4|lo)
				i += 2
				continue
			}
		}
		out = append(out, value[i])
	}
	return strings.ToValidUTF8(string(out), "�")
}

func pyUnhex(c byte) (byte, bool) {
	switch {
	case c >= '0' && c <= '9':
		return c - '0', true
	case c >= 'a' && c <= 'f':
		return c - 'a' + 10, true
	case c >= 'A' && c <= 'F':
		return c - 'A' + 10, true
	}
	return 0, false
}

// pyReIgnoreCaseLetters are the non-ASCII code points that CPython's
// re.IGNORECASE folds into the ASCII letters: U+0130 İ and U+0131 ı (which Go's
// `(?i)`, driven by unicode.SimpleFold orbits, does NOT reach) plus U+017F ſ
// and U+212A KELVIN SIGN (which it does — listed so the class is the complete
// CPython answer rather than "the two Go misses").
//
// Only reEmailMatch is widened with them: it is the one `(?i)` pattern here
// whose input is an operator- or sender-supplied address. The cue words
// ("openai", "deactivated", ...) come from OpenAI's own mail and never arrive
// spelled with a Turkish dotted I.
const pyReIgnoreCaseLetters = `\x{0130}\x{0131}\x{017F}\x{212A}`
