package settings

// This file is a targeted port of CPython's urllib.parse.urlsplit, kept to the
// exact subset ProxyProviderConfig.validated() reads off it (app.py:980-983):
//
//	parsed = urlsplit(endpoint if "://" in endpoint else f"http://{endpoint}")
//	if not parsed.hostname or parsed.port is None: raise ...
//	if parsed.username or parsed.password or parsed.path not in {"", "/"} \
//	        or parsed.query or parsed.fragment: raise ...
//
// WHY NOT net/url. Validate used to be url.Parse + strconv.Atoi, and the two
// parsers disagree about what a host may contain. urlsplit does not validate the
// host at all — it is a pure string split — whereas net/url applies RFC 3986 and
// refuses a host holding a space, a control byte, a stray '%', or any of
// | ^ ` { } \. Every one of those endpoints is ACCEPTED by the Python app and was
// REJECTED by the Go one, so a provider endpoint the user has been running for
// months (`ho st:3010`, `host%zz:3010`, a bracketed IPvFuture literal, …) could
// not be applied here at all.
//
// It also went wrong in the other direction, which is the worse half: net/url
// splits host:port at the LAST colon, urlsplit at the FIRST. "host:3010:20" is a
// ValueError to Python and, to net/url, the host "host:3010" on port 20 — a
// silently different destination for a BILLED provider session.
//
// Reference: Lib/urllib/parse.py of the CPython that runs app.py on this machine
// (3.12.0). The behaviour is pinned by TestProviderEndpointOracle, whose table
// was generated by running the real urlsplit rather than written by hand.
//
// Only the split is ported. IDNA/NFKC-aware *encoding* is not, because
// validated() never encodes: it reads five fields and throws.

import (
	"errors"
	"fmt"
	"net/netip"
	"regexp"
	"strconv"
	"strings"
)

// The two messages app.py raises itself (app.py:981 and app.py:983).
const (
	errTextHostPort   = "主机端口格式应为 hostname:port"
	errTextHostExtras = "主机端口不能包含凭据、路径或参数"
)

// DIVERGENCE (message only, never verdict): urlsplit and the .port property
// raise their own ValueErrors — "Port out of range 0-65535", "Invalid IPv6 URL",
// "An IPv4 address cannot be in brackets", … — and app.py:12533 renders whichever
// one escaped as 提供商代理配置无效: <text>. This port folds all of them into
// errTextHostPort: every one of them means the same thing to the user (this is
// not a usable hostname:port) and mixing CPython's English internals into a
// Chinese dialog reads as a crash rather than a validation message. The
// accept/reject verdict is identical, which is the half that gates a billable
// session.
func errBadHostPort() error { return errors.New(errTextHostPort) }

// pySplitResult is urllib.parse.SplitResult minus the fields validated() never
// touches (scheme). netloc is kept raw: every accessor below re-derives its
// component from it exactly as CPython's properties do.
type pySplitResult struct {
	netloc   string
	path     string
	query    string
	fragment string
}

// whatwgRemove is urllib's `for b in _UNSAFE_URL_BYTES_TO_REMOVE: url =
// url.replace(b, "")` — tab, CR and LF are deleted from ANYWHERE in the URL, not
// just the ends. That is why "ho\tst:3010" is the host "host" to Python.
var whatwgRemove = strings.NewReplacer("\t", "", "\r", "", "\n", "")

// isWHATWGTrim is _WHATWG_C0_CONTROL_OR_SPACE, U+0000..U+0020 inclusive. Note
// urlsplit only LSTRIPS it ("some applications rely on preserving trailing
// space"); the trailing end is already gone here because validated() calls
// .strip() on the endpoint first (app.py:978).
func isWHATWGTrim(r rune) bool { return r <= 0x20 }

// isSchemeChar is urllib.parse.scheme_chars.
func isSchemeChar(c byte) bool {
	return c >= 'a' && c <= 'z' || c >= 'A' && c <= 'Z' || c >= '0' && c <= '9' ||
		c == '+' || c == '-' || c == '.'
}

func isASCIIAlpha(c byte) bool { return c >= 'a' && c <= 'z' || c >= 'A' && c <= 'Z' }

// ipvFutureRe is _check_bracketed_host's `re.match(r"\Av[a-fA-F0-9]+\..+\Z", …)`.
// Go's `^`/`$` are already whole-text anchors (no (?m)) and Go's `.` already
// excludes \n, so the translation is exact.
var ipvFutureRe = regexp.MustCompile(`^v[a-fA-F0-9]+\..+$`)

// pyURLSplit ports urlsplit(url, scheme="", allow_fragments=True).
//
// A non-nil error is one of urlsplit's own ValueErrors; the caller maps it to
// errTextHostPort. The lru_cache is deliberately not reproduced.
func pyURLSplit(rawURL string) (pySplitResult, error) {
	u := whatwgRemove.Replace(strings.TrimLeftFunc(rawURL, isWHATWGTrim))

	// Scheme detection. Iterating bytes rather than runes is safe: every byte of
	// a non-ASCII rune is >= 0x80 and so fails isSchemeChar, exactly as the rune
	// itself would.
	if i := strings.IndexByte(u, ':'); i > 0 && isASCIIAlpha(u[0]) {
		valid := true
		for j := 0; j < i; j++ {
			if !isSchemeChar(u[j]) {
				valid = false
				break
			}
		}
		if valid {
			u = u[i+1:]
		}
	}

	var out pySplitResult
	if strings.HasPrefix(u, "//") {
		// _splitnetloc(url, 2): the netloc ends at the EARLIEST of / ? # — which
		// is why a netloc can never itself contain one of those three, a fact
		// pyCheckNetloc relies on.
		rest := u[2:]
		if idx := strings.IndexAny(rest, "/?#"); idx >= 0 {
			out.netloc, u = rest[:idx], rest[idx:]
		} else {
			out.netloc, u = rest, ""
		}
		open := strings.Contains(out.netloc, "[")
		closed := strings.Contains(out.netloc, "]")
		if open != closed {
			return pySplitResult{}, errors.New("Invalid IPv6 URL")
		}
		if open && closed {
			// netloc.partition('[')[2].partition(']')[0] — the text between the
			// FIRST '[' and the first ']' after it.
			after := out.netloc[strings.IndexByte(out.netloc, '[')+1:]
			bracketed, _ := pyPartition(after, ']')
			if err := pyCheckBracketedHost(bracketed); err != nil {
				return pySplitResult{}, err
			}
		}
	}
	// Fragment before query, matching urlsplit — so "host:3010#a?b" has the whole
	// "a?b" as its fragment and no query at all.
	if i := strings.IndexByte(u, '#'); i >= 0 {
		u, out.fragment = u[:i], u[i+1:]
	}
	if i := strings.IndexByte(u, '?'); i >= 0 {
		u, out.query = u[:i], u[i+1:]
	}
	if err := pyCheckNetloc(out.netloc); err != nil {
		return pySplitResult{}, err
	}
	out.path = u
	return out, nil
}

// pyCheckBracketedHost ports urllib.parse._check_bracketed_host.
//
// netip.ParseAddr is the closest match to ipaddress.ip_address for the inputs
// that can reach here: both accept an IPv6 zone ("fe80::1%eth0"), both reject an
// IPv4 literal with leading zeros, and Addr.Is4 is false for a v4-mapped v6
// address ("::ffff:1.2.3.4") just as isinstance(ip, IPv4Address) is.
func pyCheckBracketedHost(host string) error {
	if strings.HasPrefix(host, "v") {
		if !ipvFutureRe.MatchString(host) {
			return errors.New("IPvFuture address is invalid")
		}
		return nil
	}
	addr, err := netip.ParseAddr(host)
	if err != nil {
		return fmt.Errorf("%q does not appear to be an IPv4 or IPv6 address", host)
	}
	if addr.Is4() {
		return errors.New("An IPv4 address cannot be in brackets")
	}
	return nil
}

// nfkcHazard is the complete set of non-ASCII codepoints whose NFKC
// normalization contains one of / ? # @ : — the check urllib.parse._checknetloc
// performs so that a host like "℀.com" (U+2100, which NFKC-expands to "a/c")
// cannot smuggle a path or a userinfo past a naive parser.
//
// Enumerated by normalizing all 1,112,064 codepoints under this machine's
// CPython 3.12 and keeping the 19 hits; the same brute-force technique this
// package already used for upperFullReplacer and providerRegionSplitRe.
//
// A per-codepoint table is EXACT here rather than an approximation of full NFKC:
// _checknetloc only asks whether one of those five ASCII characters appears in
// the normalized string, and NFKC introduces ASCII only through per-character
// compatibility decomposition. Its composition phase merges a base and a
// combining mark into a precomposed (always non-ASCII) character, so it can
// never manufacture one of the five, and it cannot consume one either — none of
// the five participates in a composition. Verified over a random battery in
// TestCheckNetlocMatchesCPython.
var nfkcHazard = map[rune]bool{
	0x2047: true, // ⁇ DOUBLE QUESTION MARK        -> "??"
	0x2048: true, // ⁈ QUESTION EXCLAMATION MARK   -> "?!"
	0x2049: true, // ⁉ EXCLAMATION QUESTION MARK   -> "!?"
	0x2100: true, // ℀ ACCOUNT OF                  -> "a/c"
	0x2101: true, // ℁ ADDRESSED TO THE SUBJECT    -> "a/s"
	0x2105: true, // ℅ CARE OF                     -> "c/o"
	0x2106: true, // ℆ CADA UNA                    -> "c/u"
	0x2A74: true, // ⩴ DOUBLE COLON EQUAL          -> "::="
	0xFE13: true, // ︓ VERTICAL COLON              -> ":"
	0xFE16: true, // ︖ VERTICAL QUESTION MARK      -> "?"
	0xFE55: true, // ﹕ SMALL COLON                 -> ":"
	0xFE56: true, // ﹖ SMALL QUESTION MARK         -> "?"
	0xFE5F: true, // ﹟ SMALL NUMBER SIGN           -> "#"
	0xFE6B: true, // ﹫ SMALL COMMERCIAL AT         -> "@"
	0xFF03: true, // ＃ FULLWIDTH NUMBER SIGN       -> "#"
	0xFF0F: true, // ／ FULLWIDTH SOLIDUS           -> "/"
	0xFF1A: true, // ： FULLWIDTH COLON             -> ":"
	0xFF1F: true, // ？ FULLWIDTH QUESTION MARK     -> "?"
	0xFF20: true, // ＠ FULLWIDTH COMMERCIAL AT     -> "@"
}

// pyCheckNetloc ports urllib.parse._checknetloc.
//
// CPython removes @ : # ? from the netloc before normalizing ("ignore characters
// already included"), so those four are skipped here. / can never be present at
// all — _splitnetloc stopped there.
func pyCheckNetloc(netloc string) error {
	if netloc == "" || isASCIIOnly(netloc) { // str.isascii()
		return nil
	}
	for _, r := range netloc {
		switch r {
		case '@', ':', '#', '?':
			continue
		}
		if nfkcHazard[r] {
			return fmt.Errorf("netloc '%s' contains invalid characters under NFKC normalization", netloc)
		}
	}
	return nil
}

func isASCIIOnly(s string) bool {
	for i := 0; i < len(s); i++ {
		if s[i] >= 0x80 {
			return false
		}
	}
	return true
}

// hostinfo ports SplitResult._hostinfo.
//
// THE FIRST COLON, NOT THE LAST — that single line is the whole reason net/url
// could not be reused. Anything after the LAST '@' is the host part; inside it,
// a bracketed literal ends at the first ']' and the port is whatever follows a
// ':' after that, otherwise the netloc is cut at its FIRST ':'.
//
// The returned port is the raw text; "" is CPython's `if not port: port = None`.
func (r pySplitResult) hostinfo() (host, port string) {
	hostinfo := r.netloc
	if at := strings.LastIndexByte(r.netloc, '@'); at >= 0 {
		hostinfo = r.netloc[at+1:]
	}
	if open := strings.IndexByte(hostinfo, '['); open >= 0 {
		bracketed := hostinfo[open+1:]
		host, rest := pyPartition(bracketed, ']')
		_, port := pyPartition(rest, ':')
		return host, port
	}
	return pyPartition(hostinfo, ':')
}

// hostText is SplitResult.hostname's INPUT, not its output: the `.lower()` and
// the %-zone preservation are skipped because validated() only asks whether the
// hostname is truthy (app.py:981), and lower-casing cannot make a non-empty
// string empty. Anything that needs the real hostname must lower-case it with a
// FULL case mapping — see providerproxy.BuildProxyURL, which does.
func (r pySplitResult) hostText() string {
	host, _ := r.hostinfo()
	return host
}

// userinfo ports SplitResult._userinfo, flattened to two strings because
// app.py:983 tests `parsed.username or parsed.password`, i.e. TRUTHINESS. Python
// distinguishes None (no '@' at all) from "" (an empty userinfo, "@host:3010"),
// and both are falsy — so "@host:3010" and ":@host:3010" are legal endpoints.
func (r pySplitResult) userinfo() (username, password string) {
	at := strings.LastIndexByte(r.netloc, '@')
	if at < 0 {
		return "", ""
	}
	return pyPartition(r.netloc[:at], ':')
}

// port ports the SplitResult.port property of CPython 3.12:
//
//	if port.isdigit() and port.isascii(): port = int(port)
//	else: raise ValueError(f"Port could not be cast to integer value as {port!r}")
//	if not (0 <= port <= 65535): raise ValueError("Port out of range 0-65535")
//
// `isdigit() and isascii()` together mean "non-empty and every character in
// 0-9". That is NARROWER than int(text, 10), which is what older CPythons used
// here and what this port's providerproxy.pyParseInt10 still models for
// build_proxy_url: 3.12 rejects "3_010", "+3010" and " 3010", and rejects every
// non-ASCII digit ("٣٠١٠", "０３０１０") that int() would happily accept.
//
// ok is false with a nil error only for the absent port (CPython's None).
func (r pySplitResult) port() (value int, ok bool, err error) {
	_, text := r.hostinfo()
	if text == "" {
		return 0, false, nil
	}
	for i := 0; i < len(text); i++ {
		if text[i] < '0' || text[i] > '9' {
			return 0, false, fmt.Errorf("Port could not be cast to integer value as %q", text)
		}
	}
	// int() is arbitrary precision, so a 40-digit port is a RANGE error in
	// Python, not a parse error; strconv.Atoi would overflow. Leading zeros are
	// legal and significant to neither ("0080" is 80).
	digits := strings.TrimLeft(text, "0")
	if len(digits) > 5 {
		return 0, false, errors.New("Port out of range 0-65535")
	}
	if digits == "" {
		return 0, true, nil // "0", "00", …
	}
	value, aerr := strconv.Atoi(digits)
	if aerr != nil || value > 65535 {
		return 0, false, errors.New("Port out of range 0-65535")
	}
	return value, true, nil
}

// pyPartition is str.partition(sep) reduced to (head, tail); tail is "" when sep
// is absent, which is exactly what CPython's `if not port: port = None` keys off.
func pyPartition(s string, sep byte) (string, string) {
	if i := strings.IndexByte(s, sep); i >= 0 {
		return s[:i], s[i+1:]
	}
	return s, ""
}
