package alias

// pytext.go holds the CPython `str` semantics this package needs. It is a
// verbatim sibling of internal/mail/pytext.go and internal/worker/pytext.go:
// the port duplicates these helpers per package on purpose so each stays a leaf.
//
// The two rules that bite here:
//   - strings.TrimSpace is NOT str.strip(): it omits the four information
//     separators U+001C..U+001F, which Python strips.
//   - strings.ToLower is neither str.lower() nor str.casefold(). lower() differs
//     at U+0130 only; casefold() does FULL folding, so ß folds to "ss" and ſ to
//     "s" — normalize_domain_mail_domain (app.py:1753) accepts
//     "exampleß.com" as "exampless.com" purely because of that.

import (
	"regexp"
	"strings"
	"unicode"
	"unicode/utf8"
)

// pyIsSpace is str.isspace() for one character. unicode.IsSpace covers 25 of
// the 29 code points and omits the four information separators U+001C..U+001F,
// which str.strip() does remove.
func pyIsSpace(r rune) bool {
	return unicode.IsSpace(r) || (r >= 0x1c && r <= 0x1f)
}

// pyStrip is str.strip(); pyRStrip is str.rstrip().
func pyStrip(s string) string  { return strings.TrimFunc(s, pyIsSpace) }
func pyRStrip(s string) string { return strings.TrimRightFunc(s, pyIsSpace) }

// pyLower is str.lower(). Full lowercase mapping differs from Go's simple
// mapping at exactly ONE code point, U+0130 LATIN CAPITAL LETTER I WITH DOT
// ABOVE, which lowercases to two runes (i + U+0307); verified by walking
// U+0000..U+10FFFF.
//
// DIVERGENCE: CPython also applies the Greek final-sigma context rule, so
// "ΟΔΟΣ".lower() is "οδος" while this returns "οδοσ". Reproducing it needs the
// Cased/Case_Ignorable properties Go does not export, and no call site here
// lowercases Greek prose — the inputs are URLs and ASCII marker words.
func pyLower(s string) string {
	if strings.ContainsRune(s, 'İ') {
		s = strings.ReplaceAll(s, "İ", "i̇")
	}
	return strings.ToLower(s)
}

// pyFoldPairs is every code point whose str.casefold() differs from Go's
// strings.ToLower, EXCEPT the Cherokee block (a pure range rule, see
// pyFoldCherokee). Generated by walking U+0000..U+10FFFF in CPython 3.12
// (Unicode 15.0.0) and diffing against strings.ToLower; encoded as
// space-separated "<rune><replacement>" records, none of which contains a
// space. 132 records.
const pyFoldPairs = "µμ ßss İi̇ ŉʼn ſs ǰǰ ͅι " +
	"ΐΐ ΰΰ ςσ ϐβ ϑθ " +
	"ϕφ ϖπ ϰκ ϱρ ϵε ևեւ " +
	"ᏸᏰ ᏹᏱ ᏺᏲ ᏻᏳ ᏼᏴ ᏽᏵ ᲀв " +
	"ᲁд ᲂо ᲃс ᲄт ᲅт ᲆъ ᲇѣ " +
	"ᲈꙋ ẖẖ ẗẗ ẘẘ ẙẙ ẚaʾ " +
	"ẛṡ ẞss ὐὐ ὒὒ ὔὔ " +
	"ὖὖ ᾀἀι ᾁἁι ᾂἂι " +
	"ᾃἃι ᾄἄι ᾅἅι ᾆἆι " +
	"ᾇἇι ᾈἀι ᾉἁι ᾊἂι " +
	"ᾋἃι ᾌἄι ᾍἅι ᾎἆι " +
	"ᾏἇι ᾐἠι ᾑἡι ᾒἢι " +
	"ᾓἣι ᾔἤι ᾕἥι ᾖἦι " +
	"ᾗἧι ᾘἠι ᾙἡι ᾚἢι " +
	"ᾛἣι ᾜἤι ᾝἥι ᾞἦι " +
	"ᾟἧι ᾠὠι ᾡὡι ᾢὢι " +
	"ᾣὣι ᾤὤι ᾥὥι ᾦὦι " +
	"ᾧὧι ᾨὠι ᾩὡι ᾪὢι " +
	"ᾫὣι ᾬὤι ᾭὥι ᾮὦι " +
	"ᾯὧι ᾲὰι ᾳαι ᾴάι " +
	"ᾶᾶ ᾷᾶι ᾼαι ιι " +
	"ῂὴι ῃηι ῄήι ῆῆ " +
	"ῇῆι ῌηι ῒῒ " +
	"ΐΐ ῖῖ ῗῗ " +
	"ῢῢ ΰΰ ῤῤ ῦῦ " +
	"ῧῧ ῲὼι ῳωι ῴώι " +
	"ῶῶ ῷῶι ῼωι ﬀff ﬁfi ﬂfl " +
	"ﬃffi ﬄffl ﬅst ﬆst ﬓմն ﬔմե " +
	"ﬕմի ﬖվն ﬗմխ"

var pyFoldMap = buildPyFoldMap()

func buildPyFoldMap() map[rune]string {
	out := make(map[rune]string, 132)
	for _, record := range strings.Split(pyFoldPairs, " ") {
		if record == "" {
			continue
		}
		key, size := utf8.DecodeRuneInString(record)
		out[key] = record[size:]
	}
	return out
}

// pyFoldCherokee is the Cherokee half of the casefold table, which folds to
// UPPERCASE rather than lowercase: the syllabary's lowercase letters were added
// to Unicode long after the uppercase ones, so CaseFolding.txt keeps the old
// (uppercase) form as the fold target. Go's strings.ToLower goes the other way.
func pyFoldCherokee(r rune) (rune, bool) {
	switch {
	case r >= 0x13A0 && r <= 0x13F5:
		return r, true
	case r >= 0xAB70 && r <= 0xABBF:
		return r - 0xAB70 + 0x13A0, true
	}
	return 0, false
}

// pyCaseFold is str.casefold(): FULL Unicode case folding, which the Go
// standard library does not provide. ß folds to "ss" and ſ to "s", so casefold
// is NOT strings.ToLower — every deactivation / security marker in this file is
// compared against a folded haystack, and "found as compromiſed" is a match in
// Python.
func pyCaseFold(s string) string {
	if isASCII(s) {
		return strings.ToLower(s)
	}
	var b strings.Builder
	b.Grow(len(s))
	for _, r := range s {
		if v, ok := pyFoldMap[r]; ok {
			b.WriteString(v)
			continue
		}
		if v, ok := pyFoldCherokee(r); ok {
			b.WriteRune(v)
			continue
		}
		b.WriteRune(unicode.ToLower(r))
	}
	return b.String()
}

func isASCII(s string) bool {
	for i := 0; i < len(s); i++ {
		if s[i] >= utf8.RuneSelf {
			return false
		}
	}
	return true
}

// pyNormalizeEmailAddress mirrors normalize_email_address (app.py:1610).
//
// DELIBERATELY NOT models.NormalizeEmailAddress: that copy opens with
// strings.TrimSpace, which leaves U+001C..U+001F in place where str.strip()
// removes them. The regex hides the difference whenever an address is actually
// found, but a field that is NOT an address round-trips with the separators
// still attached — and "\x1f" alone then passes parse_account_line's
// `if not email_addr` guard instead of failing it.
var reNormalizeEmail = regexp.MustCompile("[A-Za-z0-9.!#$%&'*+/=?^_`{|}~-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}")

const normalizeTrimCutset = " \t\r\n\"'\u201c\u201d\u2018\u2019<>()[]{}\uff0c,;\uff1b"

func pyNormalizeEmailAddress(value string) string {
	text := pyStrip(value)
	text = strings.Trim(text, normalizeTrimCutset)
	if m := reNormalizeEmail.FindString(text); m != "" {
		return m
	}
	return text
}
