/*
  Vitest 会把生成的 Wails 桥接替换成这堵“拒绝墙”。

  下方名称与 `wailsjs/go/ui/App.js` 的 91 个导出逐字对应，每个调用都会同步
  抛错。测试如需返回值，应在自己的测试文件中 mock `../api`，不能把这里改成
  成功 Promise；否则测试可能在不知情时依赖真实后端、浏览器、租号或支付流程。
*/

/** 创建一个永远不会落到真实 Wails 后端的拒绝函数。 */
function refuse(name: string): (...args: unknown[]) => never {
  return () => {
    throw new Error(
      `wails binding ${name} was called from a test. The bridge is stubbed on purpose ` +
        `(vite.config.ts test.alias); mock ../api in the test instead.`,
    )
  }
}

export const AnswerPrompt = refuse('AnswerPrompt')
export const ApplyProviderProxySettings = refuse('ApplyProviderProxySettings')
export const AutoClassifyAccounts = refuse('AutoClassifyAccounts')
export const CancelJob = refuse('CancelJob')
export const ClearAccountWorkflow = refuse('ClearAccountWorkflow')
export const ClearAccounts = refuse('ClearAccounts')
export const ClearPhones = refuse('ClearPhones')
export const ConsumePaymentCard = refuse('ConsumePaymentCard')
export const CountProxyPoolText = refuse('CountProxyPoolText')
export const CopyExportPreview = refuse('CopyExportPreview')
export const CopySessionConversion = refuse('CopySessionConversion')
export const CreateAccountGroup = refuse('CreateAccountGroup')
export const CreateDomainMailAccounts = refuse('CreateDomainMailAccounts')
export const CreatePlusAliasAccounts = refuse('CreatePlusAliasAccounts')
export const DeleteAccountGroup = refuse('DeleteAccountGroup')
export const DeleteAccounts = refuse('DeleteAccounts')
export const Environment = refuse('Environment')
export const ExportMissingRT = refuse('ExportMissingRT')
export const ExtractMailboxCode = refuse('ExtractMailboxCode')
export const ExtractMailboxInviteLink = refuse('ExtractMailboxInviteLink')
export const GenerateLinks = refuse('GenerateLinks')
export const GetAccountDetails = refuse('GetAccountDetails')
export const GetMailboxMessage = refuse('GetMailboxMessage')
export const GetNetworkJobResult = refuse('GetNetworkJobResult')
export const ImportAccounts = refuse('ImportAccounts')
export const ImportPaymentCards = refuse('ImportPaymentCards')
export const ImportPhones = refuse('ImportPhones')
export const ListAccounts = refuse('ListAccounts')
export const ListJobs = refuse('ListJobs')
export const ListMailboxFolders = refuse('ListMailboxFolders')
export const ListMailboxMessages = refuse('ListMailboxMessages')
export const ListPaymentCards = refuse('ListPaymentCards')
export const ListPhones = refuse('ListPhones')
export const LoadLogs = refuse('LoadLogs')
export const LoadSettings = refuse('LoadSettings')
export const LoadSummary = refuse('LoadSummary')
export const Log = refuse('Log')
export const MergeManualSession = refuse('MergeManualSession')
export const MoveAccountsToGroup = refuse('MoveAccountsToGroup')
export const OpenAccountFile = refuse('OpenAccountFile')
export const OpenPaymentExtensionDirectory = refuse('OpenPaymentExtensionDirectory')
export const PatchSettings = refuse('PatchSettings')
export const PrepareSub2APIExport = refuse('PrepareSub2APIExport')
export const PreviewExport = refuse('PreviewExport')
export const ProviderProxyStatuses = refuse('ProviderProxyStatuses')
export const RenameAccountGroup = refuse('RenameAccountGroup')
export const ReplaceManualSession = refuse('ReplaceManualSession')
export const ReplacePayPalCardHead = refuse('ReplacePayPalCardHead')
export const ResetPaymentCards = refuse('ResetPaymentCards')
export const ResetPhones = refuse('ResetPhones')
export const SaveExport = refuse('SaveExport')
export const SaveSettings = refuse('SaveSettings')
export const SaveSub2APIExport = refuse('SaveSub2APIExport')
export const SelectLogAccount = refuse('SelectLogAccount')
export const SetAccountType = refuse('SetAccountType')
export const StartAcceptWorkspaceInvite = refuse('StartAcceptWorkspaceInvite')
export const StartBatchGenerateLinks = refuse('StartBatchGenerateLinks')
export const StartBatchRelink = refuse('StartBatchRelink')
export const StartBatchRegister = refuse('StartBatchRegister')
export const StartCPAExportRefresh = refuse('StartCPAExportRefresh')
export const StartCloudMailProbe = refuse('StartCloudMailProbe')
export const StartCloudMailTokenGeneration = refuse('StartCloudMailTokenGeneration')
export const StartDeactivationScan = refuse('StartDeactivationScan')
export const StartDomainRandomRT = refuse('StartDomainRandomRT')
export const StartExternalOAuth = refuse('StartExternalOAuth')
export const StartK12AcceptAndRefresh = refuse('StartK12AcceptAndRefresh')
export const StartK12RegisterAndJoin = refuse('StartK12RegisterAndJoin')
export const StartK12RequestInvite = refuse('StartK12RequestInvite')
export const StartKeepLogin = refuse('StartKeepLogin')
export const StartManualLoginCode = refuse('StartManualLoginCode')
export const StartManualPhoneCode = refuse('StartManualPhoneCode')
export const StartOAuthAuthorizeRT = refuse('StartOAuthAuthorizeRT')
export const StartOpenPaymentWindow = refuse('StartOpenPaymentWindow')
export const StartOpenPaymentWindows = refuse('StartOpenPaymentWindows')
export const StartOpenSessionReader = refuse('StartOpenSessionReader')
export const StartProtocolRegisterSession = refuse('StartProtocolRegisterSession')
export const StartProxyPoolCleanup = refuse('StartProxyPoolCleanup')
export const StartProxyPoolPrecheck = refuse('StartProxyPoolPrecheck')
export const StartRefreshAccountType = refuse('StartRefreshAccountType')
export const StartRefreshSession = refuse('StartRefreshSession')
export const StartRegister = refuse('StartRegister')
export const StartSMSBowerReadTest = refuse('StartSMSBowerReadTest')
export const StartSub2APIExport = refuse('StartSub2APIExport')
export const StartTeamInvite = refuse('StartTeamInvite')
export const StartTeamInviteScanJoin = refuse('StartTeamInviteScanJoin')
export const StartTeamLeave = refuse('StartTeamLeave')
export const StartTrialEligibility = refuse('StartTrialEligibility')
export const StartTurnstileProbe = refuse('StartTurnstileProbe')
export const StopAll = refuse('StopAll')
export const StopProviderProxyPools = refuse('StopProviderProxyPools')
export const SwitchPaymentWindowProxy = refuse('SwitchPaymentWindowProxy')
