package openai

// pytext.go holds the CPython `str` semantics this package needs. It is a
// verbatim sibling of internal/mail/pytext.go and internal/worker/pytext.go:
// the port duplicates these helpers per package on purpose so each stays a leaf.
//
// The two rules that bite here:
//   - strings.TrimSpace is NOT str.strip(): it omits the four information
//     separators U+001C..U+001F, which Python strips.
//   - strings.ToLower is neither str.lower() nor str.casefold(). lower() differs
//     at U+0130 only; casefold() does FULL folding, so ß folds to "ss" and ſ to
//     "s" — the transient-error marker "ssl" (app.py:5622) and the
//     Team role names are matched against a folded haystack.

import (
	"fmt"
	"math"
	"sort"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"
)

// pyWSClass is the BODY of a character class equal to Python's str-mode `\s`.
// RE2's own `\s` is [\t\n\f\r ] — no VT, no NBSP, no ideographic space.
const pyWSClass = `\s\x{000B}\x{001C}-\x{001F}\x{0085}\p{Z}`

// pyIsSpace is str.isspace() for one character. unicode.IsSpace covers 25 of
// the 29 code points and omits the four information separators U+001C..U+001F,
// which str.strip() does remove.
func pyIsSpace(r rune) bool {
	return unicode.IsSpace(r) || (r >= 0x1c && r <= 0x1f)
}

// pyStrip is str.strip(); pyRStrip is str.rstrip().
func pyStrip(s string) string  { return strings.TrimFunc(s, pyIsSpace) }
func pyRStrip(s string) string { return strings.TrimRightFunc(s, pyIsSpace) }

// pyLower is str.lower(). Full lowercase mapping differs from Go's simple
// mapping at exactly ONE code point, U+0130 LATIN CAPITAL LETTER I WITH DOT
// ABOVE, which lowercases to two runes (i + U+0307); verified by walking
// U+0000..U+10FFFF.
//
// DIVERGENCE: CPython also applies the Greek final-sigma context rule, so
// "ΟΔΟΣ".lower() is "οδος" while this returns "οδοσ". Reproducing it needs the
// Cased/Case_Ignorable properties Go does not export, and no call site here
// lowercases Greek prose — the inputs are URLs and ASCII marker words.
func pyLower(s string) string {
	if strings.ContainsRune(s, 'İ') {
		s = strings.ReplaceAll(s, "İ", "i̇")
	}
	return strings.ToLower(s)
}

// pyFoldPairs is every code point whose str.casefold() differs from Go's
// strings.ToLower, EXCEPT the Cherokee block (a pure range rule, see
// pyFoldCherokee). Generated by walking U+0000..U+10FFFF in CPython 3.12
// (Unicode 15.0.0) and diffing against strings.ToLower; encoded as
// space-separated "<rune><replacement>" records, none of which contains a
// space. 132 records.
const pyFoldPairs = "µμ ßss İi̇ ŉʼn ſs ǰǰ ͅι " +
	"ΐΐ ΰΰ ςσ ϐβ ϑθ " +
	"ϕφ ϖπ ϰκ ϱρ ϵε ևեւ " +
	"ᏸᏰ ᏹᏱ ᏺᏲ ᏻᏳ ᏼᏴ ᏽᏵ ᲀв " +
	"ᲁд ᲂо ᲃс ᲄт ᲅт ᲆъ ᲇѣ " +
	"ᲈꙋ ẖẖ ẗẗ ẘẘ ẙẙ ẚaʾ " +
	"ẛṡ ẞss ὐὐ ὒὒ ὔὔ " +
	"ὖὖ ᾀἀι ᾁἁι ᾂἂι " +
	"ᾃἃι ᾄἄι ᾅἅι ᾆἆι " +
	"ᾇἇι ᾈἀι ᾉἁι ᾊἂι " +
	"ᾋἃι ᾌἄι ᾍἅι ᾎἆι " +
	"ᾏἇι ᾐἠι ᾑἡι ᾒἢι " +
	"ᾓἣι ᾔἤι ᾕἥι ᾖἦι " +
	"ᾗἧι ᾘἠι ᾙἡι ᾚἢι " +
	"ᾛἣι ᾜἤι ᾝἥι ᾞἦι " +
	"ᾟἧι ᾠὠι ᾡὡι ᾢὢι " +
	"ᾣὣι ᾤὤι ᾥὥι ᾦὦι " +
	"ᾧὧι ᾨὠι ᾩὡι ᾪὢι " +
	"ᾫὣι ᾬὤι ᾭὥι ᾮὦι " +
	"ᾯὧι ᾲὰι ᾳαι ᾴάι " +
	"ᾶᾶ ᾷᾶι ᾼαι ιι " +
	"ῂὴι ῃηι ῄήι ῆῆ " +
	"ῇῆι ῌηι ῒῒ " +
	"ΐΐ ῖῖ ῗῗ " +
	"ῢῢ ΰΰ ῤῤ ῦῦ " +
	"ῧῧ ῲὼι ῳωι ῴώι " +
	"ῶῶ ῷῶι ῼωι ﬀff ﬁfi ﬂfl " +
	"ﬃffi ﬄffl ﬅst ﬆst ﬓմն ﬔմե " +
	"ﬕմի ﬖվն ﬗմխ"

var pyFoldMap = buildPyFoldMap()

func buildPyFoldMap() map[rune]string {
	out := make(map[rune]string, 132)
	for _, record := range strings.Split(pyFoldPairs, " ") {
		if record == "" {
			continue
		}
		key, size := utf8.DecodeRuneInString(record)
		out[key] = record[size:]
	}
	return out
}

// pyFoldCherokee is the Cherokee half of the casefold table, which folds to
// UPPERCASE rather than lowercase: the syllabary's lowercase letters were added
// to Unicode long after the uppercase ones, so CaseFolding.txt keeps the old
// (uppercase) form as the fold target. Go's strings.ToLower goes the other way.
func pyFoldCherokee(r rune) (rune, bool) {
	switch {
	case r >= 0x13A0 && r <= 0x13F5:
		return r, true
	case r >= 0xAB70 && r <= 0xABBF:
		return r - 0xAB70 + 0x13A0, true
	}
	return 0, false
}

// pyCaseFold is str.casefold(): FULL Unicode case folding, which the Go
// standard library does not provide. ß folds to "ss" and ſ to "s", so casefold
// is NOT strings.ToLower — every deactivation / security marker in this file is
// compared against a folded haystack, and "found as compromiſed" is a match in
// Python.
func pyCaseFold(s string) string {
	if isASCII(s) {
		return strings.ToLower(s)
	}
	var b strings.Builder
	b.Grow(len(s))
	for _, r := range s {
		if v, ok := pyFoldMap[r]; ok {
			b.WriteString(v)
			continue
		}
		if v, ok := pyFoldCherokee(r); ok {
			b.WriteRune(v)
			continue
		}
		b.WriteRune(unicode.ToLower(r))
	}
	return b.String()
}

// pyDigitValue is Python's int(ch) for one character: the decimal value of a
// Unicode digit, or (0, false) outside category Nd.
//
// Nd is laid out as complete, aligned runs of ten, so the offset from the start
// of the containing range modulo ten IS the value. Several ranges hold more
// than one run (U+1D7CE..U+1D7FF is five), which is why walking backwards to
// the nearest non-Nd rune would answer 9 for U+1D7D8 MATHEMATICAL DOUBLE-STRUCK
// DIGIT ZERO.
func pyDigitValue(r rune) (int, bool) {
	if r <= unicode.MaxLatin1 {
		if r >= '0' && r <= '9' {
			return int(r - '0'), true
		}
		return 0, false
	}
	for _, rg := range unicode.Nd.R16 {
		if rune(rg.Lo) <= r && r <= rune(rg.Hi) && rg.Stride == 1 {
			return int((r - rune(rg.Lo)) % 10), true
		}
	}
	for _, rg := range unicode.Nd.R32 {
		if rune(rg.Lo) <= r && r <= rune(rg.Hi) && rg.Stride == 1 {
			return int((r - rune(rg.Lo)) % 10), true
		}
	}
	return 0, false
}

// pyFoldDigits rewrites every Unicode decimal digit as its ASCII spelling.
// CPython's int()/float() accept "１７００" and "٤٢"; Go's strconv does not.
func pyFoldDigits(s string) string {
	var b strings.Builder
	b.Grow(len(s))
	for _, r := range s {
		if v, ok := pyDigitValue(r); ok {
			b.WriteByte(byte('0' + v))
			continue
		}
		b.WriteRune(r)
	}
	return b.String()
}

func isASCII(s string) bool {
	for i := 0; i < len(s); i++ {
		if s[i] >= utf8.RuneSelf {
			return false
		}
	}
	return true
}

// pyStr is Python's str(v) over json.loads output, and pyRepr the form str()
// uses for items INSIDE a container. fmt's "%v" renders a list as "[1 2]" and a
// map as "map[a:1]", where Python writes "[1, 2]" and "{'a': 1}" —
// first_non_empty (app.py:2667) stringifies whatever a claim holds, so a
// list-valued claim ends up in an account_id or a log line.
func pyStr(v any) string {
	switch t := v.(type) {
	case nil:
		return "None"
	case string:
		return t
	case bool:
		if t {
			return "True"
		}
		return "False"
	case float64:
		// CPython's json.loads yields an int for an integral JSON number, so
		// str() prints no ".0" and never an exponent.
		if t == math.Trunc(t) && math.Abs(t) < 1e16 {
			return strconv.FormatInt(int64(t), 10)
		}
		return strconv.FormatFloat(t, 'g', -1, 64)
	case []any:
		parts := make([]string, 0, len(t))
		for _, item := range t {
			parts = append(parts, pyRepr(item))
		}
		return "[" + strings.Join(parts, ", ") + "]"
	case *teamObject:
		parts := make([]string, 0, len(t.Keys()))
		for _, k := range t.Keys() {
			parts = append(parts, pyRepr(k)+": "+pyRepr(t.Get(k)))
		}
		return "{" + strings.Join(parts, ", ") + "}"
	case map[string]any:
		// Go maps have no order where CPython dicts do; sorted is the only
		// deterministic fallback. Decode through DecodeOrderedJSON to keep
		// document order — that lands in the *teamObject case above.
		keys := make([]string, 0, len(t))
		for k := range t {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		parts := make([]string, 0, len(keys))
		for _, k := range keys {
			parts = append(parts, pyRepr(k)+": "+pyRepr(t[k]))
		}
		return "{" + strings.Join(parts, ", ") + "}"
	}
	return fmt.Sprintf("%v", v)
}

// pyRepr is repr(v): only strings differ from str(), by gaining quotes.
func pyRepr(v any) string {
	s, ok := v.(string)
	if !ok {
		return pyStr(v)
	}
	quote := "'"
	if strings.Contains(s, "'") && !strings.Contains(s, `"`) {
		quote = `"`
	}
	var b strings.Builder
	b.WriteString(quote)
	for _, r := range s {
		switch {
		case r == '\\':
			b.WriteString(`\\`)
		case string(r) == quote:
			b.WriteString(`\` + quote)
		case r == '\n':
			b.WriteString(`\n`)
		case r == '\r':
			b.WriteString(`\r`)
		case r == '\t':
			b.WriteString(`\t`)
		default:
			b.WriteRune(r)
		}
	}
	b.WriteString(quote)
	return b.String()
}
