// Package proxypool ports app.py's manual proxy-pool layer: the input
// normalizer (app.py:2396 normalize_proxy_url), the pool-text parser
// (app.py:2421 parse_proxy_pool_text), the four rotating pools the Tk app kept
// inside Text widgets (app.py:17316 _rotate_proxy_pool_values) and the
// 代理模式=全走本地代理 gate (app.py:16712 _local_proxy_only_enabled) that forces
// every pool read and every reuse-proxy read to come back empty.
//
// proxyhealth has its own unexported normalizeProxyURL; it is a deliberately
// minimal scheme-fixer for already-stored URLs. This one is the full UI-input
// parser and is not interchangeable with it.
package proxypool

import (
	"errors"
	"strings"
	"unicode"
)

// pySpaceChars is Python re's \s for str patterns, which is Unicode-aware and
// equal to str.isspace(). Go's RE2 \s is [\t\n\f\r ] — no \v, no U+0085, no
// NBSP, no Unicode separators — so every ported pattern must spell the class
// out or lines carrying NBSP/全角空格 silently stop tokenising.
const pySpaceChars = `\t\n\v\f\r \x{0085}\x{001c}-\x{001f}\p{Z}`

// isPySpace matches Python's str.isspace(). unicode.IsSpace covers the same set
// except the C0 separators U+001C..U+001F, which Python does treat as space.
func isPySpace(r rune) bool {
	return unicode.IsSpace(r) || (r >= 0x1c && r <= 0x1f)
}

// pyStrip is str.strip() with no argument.
func pyStrip(s string) string {
	return strings.TrimFunc(s, isPySpace)
}

// isPyWord matches Python re's \w for str patterns (Unicode alphanumeric or
// underscore). RE2's \w is ASCII-only, which changes \b results around CJK.
func isPyWord(r rune) bool {
	return r == '_' || unicode.IsLetter(r) || unicode.IsDigit(r) || unicode.IsNumber(r)
}

// pyDigitExtra holds the code points str.isdigit() accepts that Go's
// unicode.IsDigit (category Nd only) rejects — Unicode Numeric_Type=Digit:
// superscripts, circled/parenthesised digits, Ethiopic, Kharoshthi, Chakma…
// Generated by enumerating chr(c).isdigit() and unicodedata.category(chr(c))
// against this repo's CPython; every Nd code point is also isdigit(), so Nd
// plus this table is exactly str.isdigit().
var pyDigitExtra = &unicode.RangeTable{
	R16: []unicode.Range16{
		{Lo: 0x00b2, Hi: 0x00b3, Stride: 1},
		{Lo: 0x00b9, Hi: 0x00b9, Stride: 1},
		{Lo: 0x1369, Hi: 0x1371, Stride: 1},
		{Lo: 0x19da, Hi: 0x19da, Stride: 1},
		{Lo: 0x2070, Hi: 0x2070, Stride: 1},
		{Lo: 0x2074, Hi: 0x2079, Stride: 1},
		{Lo: 0x2080, Hi: 0x2089, Stride: 1},
		{Lo: 0x2460, Hi: 0x2468, Stride: 1},
		{Lo: 0x2474, Hi: 0x247c, Stride: 1},
		{Lo: 0x2488, Hi: 0x2490, Stride: 1},
		{Lo: 0x24ea, Hi: 0x24ea, Stride: 1},
		{Lo: 0x24f5, Hi: 0x24fd, Stride: 1},
		{Lo: 0x24ff, Hi: 0x24ff, Stride: 1},
		{Lo: 0x2776, Hi: 0x277e, Stride: 1},
		{Lo: 0x2780, Hi: 0x2788, Stride: 1},
		{Lo: 0x278a, Hi: 0x2792, Stride: 1},
	},
	R32: []unicode.Range32{
		{Lo: 0x10a40, Hi: 0x10a43, Stride: 1},
		{Lo: 0x10e60, Hi: 0x10e68, Stride: 1},
		{Lo: 0x11052, Hi: 0x1105a, Stride: 1},
		{Lo: 0x1f100, Hi: 0x1f10a, Stride: 1},
	},
	LatinOffset: 2,
}

// pyIsDigit is str.isdigit(), which app.py:2353/2368/2391 use as the port test.
// The wider-than-Nd set is not academic: "1.2.3.4:8080²:u:p" is a valid
// host:port:user:pass line to Python (it yields http://u:p@1.2.3.4:8080²) and
// was silently rejected by an Nd-only port. Python behaviour wins; whatever
// dials the result is where a bad port must be caught, exactly as in app.py.
func pyIsDigit(s string) bool {
	if s == "" {
		return false
	}
	for _, r := range s {
		if !unicode.IsDigit(r) && !unicode.Is(pyDigitExtra, r) {
			return false
		}
	}
	return true
}

// pySplitlines is str.splitlines(): it breaks on far more than "\n" (\v, \f,
// \x1c-\x1e, \x85, U+2028, U+2029) and yields no trailing empty element.
// strings.Split(s, "\n") gets both of those wrong.
func pySplitlines(s string) []string {
	var out []string
	start := 0
	runes := []rune(s)
	for i := 0; i < len(runes); i++ {
		r := runes[i]
		isBreak := r == '\n' || r == '\r' || r == '\v' || r == '\f' ||
			r == 0x1c || r == 0x1d || r == 0x1e || r == 0x85 || r == 0x2028 || r == 0x2029
		if !isBreak {
			continue
		}
		out = append(out, string(runes[start:i]))
		if r == '\r' && i+1 < len(runes) && runes[i+1] == '\n' {
			i++
		}
		start = i + 1
	}
	if start < len(runes) {
		out = append(out, string(runes[start:]))
	}
	return out
}

// pyQuote is urllib.parse.quote(value, safe="") — UTF-8 bytes, uppercase hex,
// and only the RFC 3986 unreserved set left alone. net/url has no equivalent:
// QueryEscape turns ' ' into '+' and PathEscape leaves ':' '@' '&' untouched,
// either of which corrupts a proxy password.
func pyQuote(s string) string {
	const alwaysSafe = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_.-~"
	const hex = "0123456789ABCDEF"
	var b strings.Builder
	for i := 0; i < len(s); i++ {
		c := s[i]
		if strings.IndexByte(alwaysSafe, c) >= 0 {
			b.WriteByte(c)
			continue
		}
		b.WriteByte('%')
		b.WriteByte(hex[c>>4])
		b.WriteByte(hex[c&0x0f])
	}
	return b.String()
}

// splitResult mirrors urllib.parse.SplitResult.
type splitResult struct {
	Scheme, Netloc, Path, Query, Fragment string
}

func isSchemeChar(r rune) bool {
	return (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') ||
		r == '+' || r == '-' || r == '.'
}

// urlsplit ports urllib.parse.urlsplit. Hand-rolled because net/url.Parse
// percent-decodes userinfo, rejects inputs Python accepts, and re-encodes on
// String(); app.py's proxy strings must survive byte-for-byte.
//
// DIVERGENCE: CPython's urlsplit RAISES ValueError on an unbalanced bracket, a
// bad bracketed host and a netloc that grows a "/?#@:" under NFKC. This one
// never fails, because its only caller here is _join_proxy_url (app.py:2219),
// which does NOT catch — so `normalize_proxy_url("h:1 [abc]:2")` is a genuine
// traceback in app.py while the Go port returns a URL. Reproducing the crash
// would take down a worker goroutine for a malformed pool line, which is worse
// than the string being slightly wrong. MaskProxyURL, whose Python original
// DOES catch (app.py:2568-2575), gets the failing behaviour via
// netlocValueError instead.
func urlsplit(raw string) splitResult {
	// CPython 3.12 lstrips C0-control-or-space and deletes tab/CR/LF anywhere.
	// It deliberately does NOT rstrip ("some applications rely on preserving
	// trailing space"), so urlsplit("http://a  ").netloc is "a  " — trimming the
	// right-hand side here would silently repair endpoints Python leaves broken.
	u := strings.Map(func(r rune) rune {
		if r == '\t' || r == '\r' || r == '\n' {
			return -1
		}
		return r
	}, raw)
	u = strings.TrimLeftFunc(u, func(r rune) bool { return r <= 0x20 })

	var res splitResult
	if i := strings.IndexByte(u, ':'); i > 0 {
		first := u[0]
		if (first >= 'a' && first <= 'z') || (first >= 'A' && first <= 'Z') {
			ok := true
			for _, c := range u[:i] {
				if !isSchemeChar(c) {
					ok = false
					break
				}
			}
			if ok {
				res.Scheme = strings.ToLower(u[:i])
				u = u[i+1:]
			}
		}
	}
	if strings.HasPrefix(u, "//") {
		// _splitnetloc: netloc runs to the first of / ? # after the "//".
		end := len(u)
		for i := 2; i < len(u); i++ {
			if u[i] == '/' || u[i] == '?' || u[i] == '#' {
				end = i
				break
			}
		}
		res.Netloc, u = u[2:end], u[end:]
	}
	// Python splits the fragment before the query, after the netloc.
	if k := strings.IndexByte(u, '#'); k >= 0 {
		res.Fragment, u = u[k+1:], u[:k]
	}
	if k := strings.IndexByte(u, '?'); k >= 0 {
		res.Query, u = u[k+1:], u[:k]
	}
	res.Path = u
	return res
}

// usesNetloc is urllib.parse.uses_netloc, which urlunsplit consults to decide
// whether a scheme wants a "//" even with an empty netloc.
var usesNetloc = map[string]bool{
	"": true, "file": true, "ftp": true, "git": true, "git+ssh": true,
	"gopher": true, "http": true, "https": true, "imap": true,
	"itms-services": true, "mms": true, "nfs": true, "nntp": true,
	"prospero": true, "rsync": true, "rtsp": true, "rtsps": true, "rtspu": true,
	"sftp": true, "shttp": true, "snews": true, "svn": true, "svn+ssh": true,
	"telnet": true, "wais": true, "ws": true, "wss": true,
}

// urlunsplit ports urllib.parse.urlunsplit. The guard is
// `netloc or (scheme and scheme in uses_netloc and url[:2] != '//')`, NOT
// "netloc or the path already starts with //": with scheme="http", netloc=""
// and path="/p" Python emits "http:///p" (three slashes) and with scheme=""
// and path="//x" it emits "//x" unchanged. `curl -x http:///p` reaches the
// first of those through _join_proxy_url (app.py:2236).
func urlunsplit(scheme, netloc, path, query, fragment string) string {
	u := path
	if netloc != "" || (scheme != "" && usesNetloc[scheme] && !strings.HasPrefix(u, "//")) {
		if u != "" && !strings.HasPrefix(u, "/") {
			u = "/" + u
		}
		u = "//" + netloc + u
	}
	if scheme != "" {
		u = scheme + ":" + u
	}
	if query != "" {
		u = u + "?" + query
	}
	if fragment != "" {
		u = u + "#" + fragment
	}
	return u
}

// shlexSplit ports shlex.split(text, posix=True) (whitespace_split=True,
// commenters=""), used by app.py:2271 and app.py:2379. An unterminated quote is
// a ValueError in Python and both call sites turn that into "".
func shlexSplit(s string) ([]string, error) {
	runes := []rune(s)
	pos := 0
	var out []string
	for {
		tok, ok, err := shlexReadToken(runes, &pos)
		if err != nil {
			return nil, err
		}
		if !ok {
			return out, nil
		}
		out = append(out, tok)
	}
}

// shlexSpace is shlex's default whitespace set — space/tab/CR/LF only. It is
// NOT Python's \s: a NBSP does not split a shlex token. _clean_proxy_input
// having already folded NBSP and U+3000 to " " is what makes this work.
func shlexSpace(r rune) bool {
	return r == ' ' || r == '\t' || r == '\r' || r == '\n'
}

func shlexReadToken(runes []rune, pos *int) (string, bool, error) {
	const (
		stSpace  = ' '
		stWord   = 'a'
		stEscape = '\\'
	)
	state := rune(stSpace)
	escapedState := rune(stWord)
	quoted := false
	var token []rune
	done := false

	for !done {
		eof := *pos >= len(runes)
		var c rune
		if !eof {
			c = runes[*pos]
			*pos++
		}
		switch state {
		case stSpace:
			if eof {
				return "", false, nil
			}
			switch {
			case shlexSpace(c):
				// token is still empty here, so Python always continues.
			case c == stEscape:
				escapedState = stWord
				state = stEscape
			case c == '\'' || c == '"':
				state = c
			default:
				token = append(token, c)
				state = stWord
			}
		case '\'', '"':
			quoted = true
			if eof {
				return "", false, errors.New("No closing quotation")
			}
			switch {
			case c == state:
				state = stWord
			case c == stEscape && state == '"':
				// escapedquotes is '"' only: backslash is literal inside ''.
				escapedState = state
				state = stEscape
			default:
				token = append(token, c)
			}
		case stEscape:
			if eof {
				return "", false, errors.New("No escaped character")
			}
			if (escapedState == '\'' || escapedState == '"') && c != stEscape && c != escapedState {
				token = append(token, stEscape)
			}
			token = append(token, c)
			state = escapedState
		default: // stWord
			if eof {
				done = true
				break
			}
			switch {
			case shlexSpace(c):
				state = stSpace
				if len(token) > 0 || quoted {
					done = true
				}
			case c == '\'' || c == '"':
				state = c
			case c == stEscape:
				escapedState = stWord
				state = stEscape
			default:
				token = append(token, c)
			}
		}
	}
	// posix read_token: an unquoted empty result is the EOF sentinel.
	if !quoted && len(token) == 0 {
		return "", false, nil
	}
	return string(token), true, nil
}

// stripWrappingQuotes ports _strip_wrapping_quotes (app.py:2261).
func stripWrappingQuotes(value string) string {
	text := pyStrip(value)
	// Byte indexing is safe: a UTF-8 continuation byte is never 0x22/0x27, so a
	// single multi-byte rune can never look like a matched quote pair.
	if len(text) >= 2 {
		first, last := text[0], text[len(text)-1]
		if first == last && (first == '\'' || first == '"') {
			return pyStrip(text[1 : len(text)-1])
		}
	}
	return text
}

func splitProxyUserinfo(userinfo string) (string, string) {
	if i := strings.IndexByte(userinfo, ':'); i >= 0 {
		return userinfo[:i], userinfo[i+1:]
	}
	return userinfo, ""
}

// joinProxyURL ports _join_proxy_url (app.py:2214).
func joinProxyURL(scheme, endpoint, userinfo string) string {
	endpoint = pyStrip(endpoint)
	if endpoint == "" {
		return ""
	}
	var netloc, path, query, fragment string
	if strings.Contains(endpoint, "://") {
		parsed := urlsplit(endpoint)
		if parsed.Scheme != "" {
			scheme = parsed.Scheme
		}
		netloc, path, query, fragment = parsed.Netloc, parsed.Path, parsed.Query, parsed.Fragment
	} else {
		netloc = strings.Trim(endpoint, "/")
	}
	if userinfo != "" && !strings.Contains(netloc, "@") {
		username, password := splitProxyUserinfo(userinfo)
		auth := pyQuote(username)
		if password != "" {
			auth = auth + ":" + pyQuote(password)
		}
		netloc = auth + "@" + netloc
	}
	return urlunsplit(scheme, netloc, path, query, fragment)
}

var proxyInputReplacer = strings.NewReplacer(
	"\u201c", `"`,
	"\u201d", `"`,
	"\u2018", "'",
	"\u2019", "'",
	"\uff1a", ":",
	"\u00a0", " ",
	"\u3000", " ",
)

// cleanProxyInput ports _clean_proxy_input (app.py:2239).
func cleanProxyInput(value string) string {
	text := pyStrip(value)
	if text == "" {
		return ""
	}
	text = pyStrip(proxyInputReplacer.Replace(text))
	text = strings.Trim(text, "`")
	// Users paste the whole PowerShell prompt; keep only the curl command body.
	if idx := findCurlTokenStart(text); idx > 0 {
		text = pyStrip(text[idx:])
	}
	return text
}

// findCurlTokenStart implements re.search(r"(?i)(?:^|\s)(curl(?:\.exe)?)(?=\s|$)")
// and returns the byte offset of group 1, or -1. Written by hand because RE2 has
// no lookahead and because Python's \s here is Unicode-aware.
func findCurlTokenStart(text string) int {
	runes := []rune(text)
	offsets := make([]int, len(runes)+1)
	off := 0
	for i, r := range runes {
		offsets[i] = off
		off += len(string(r))
	}
	offsets[len(runes)] = off

	for i := 0; i < len(runes); i++ {
		if i > 0 && !isPySpace(runes[i-1]) {
			continue // must be at start-of-text or preceded by whitespace
		}
		for _, word := range []string{"curl.exe", "curl"} {
			n := len([]rune(word))
			if i+n > len(runes) {
				continue
			}
			if !strings.EqualFold(string(runes[i:i+n]), word) {
				continue
			}
			if i+n < len(runes) && !isPySpace(runes[i+n]) {
				continue // (?=\s|$)
			}
			return offsets[i]
		}
	}
	return -1
}

// hasCurlPrefix implements re.match(r"(?i)^curl(?:\.exe)?\b") from
// parse_proxy_pool_text (app.py:2427). \b is Unicode-aware in Python, so
// "curl代理" does NOT match — RE2's ASCII \b would say it does.
func hasCurlPrefix(line string) bool {
	runes := []rune(line)
	for _, word := range []string{"curl.exe", "curl"} {
		n := len([]rune(word))
		if len(runes) < n || !strings.EqualFold(string(runes[:n]), word) {
			continue
		}
		// The char before the boundary ('l' or 'e') is always a word char, so a
		// boundary exists iff the next char is a non-word char or end-of-string.
		if n == len(runes) || !isPyWord(runes[n]) {
			return true
		}
	}
	return false
}

// proxyURLFromCurlCommand ports _proxy_url_from_curl_command (app.py:2268).
func proxyURLFromCurlCommand(text, defaultScheme string) string {
	text = cleanProxyInput(text)
	tokens, err := shlexSplit(text)
	if err != nil {
		return ""
	}
	if len(tokens) == 0 {
		return ""
	}
	head := strings.ToLower(tokens[0])
	if head != "curl" && head != "curl.exe" {
		return ""
	}

	proxyEndpoint := ""
	proxyUserinfo := ""
	scheme := defaultScheme
	applyEndpoint := func(value string) {
		proxyEndpoint = value
		if strings.Contains(proxyEndpoint, "://") {
			if s := urlsplit(proxyEndpoint).Scheme; s != "" {
				scheme = s
			}
		}
	}

	for index := 1; index < len(tokens); {
		token := tokens[index]
		lower := strings.ToLower(token)
		nextValue := ""
		if index+1 < len(tokens) {
			nextValue = tokens[index+1]
		}
		switch {
		case (lower == "-x" || lower == "--proxy" || lower == "--preproxy") && nextValue != "":
			applyEndpoint(nextValue)
			index += 2
		case strings.HasPrefix(lower, "--proxy="):
			applyEndpoint(token[len("--proxy="):])
			index++
		case lower == "--socks5" && nextValue != "":
			proxyEndpoint = nextValue
			scheme = "socks5h"
			index += 2
		case strings.HasPrefix(lower, "--socks5="):
			proxyEndpoint = token[len("--socks5="):]
			scheme = "socks5h"
			index++
		case (lower == "--socks5-hostname" || lower == "--socks5h") && nextValue != "":
			proxyEndpoint = nextValue
			scheme = "socks5h"
			index += 2
		case strings.HasPrefix(lower, "--socks5-hostname="):
			proxyEndpoint = token[len("--socks5-hostname="):]
			scheme = "socks5h"
			index++
		case strings.HasPrefix(lower, "--socks5h="):
			proxyEndpoint = token[len("--socks5h="):]
			scheme = "socks5h"
			index++
		case (lower == "-u" || lower == "--user" || lower == "--proxy-user") && nextValue != "":
			// app.py's set is {-u, --user, "-U".lower(), --proxy-user}; "-U".lower()
			// is "-u", so the uppercase form only ever arrives here case-folded.
			proxyUserinfo = nextValue
			index += 2
		case strings.HasPrefix(lower, "-u") && lower != "-u" && !strings.HasPrefix(lower, "--"):
			// Attached form -uUSER:PASS. app.py repeats this branch a second time
			// for "-U", but "-U".lower() == "-u" makes that copy unreachable.
			proxyUserinfo = token[2:]
			index++
		case strings.HasPrefix(lower, "--proxy-user="):
			proxyUserinfo = token[len("--proxy-user="):]
			index++
		default:
			index++
		}
	}

	if proxyEndpoint == "" {
		return ""
	}
	return joinProxyURL(scheme, stripWrappingQuotes(proxyEndpoint), stripWrappingQuotes(proxyUserinfo))
}

// proxyURLFromSchemeColonParts ports _proxy_url_from_scheme_colon_parts (app.py:2340).
func proxyURLFromSchemeColonParts(text string) string {
	m := reSchemeColonParts.FindStringSubmatch(text)
	if m == nil {
		return ""
	}
	scheme := strings.ToLower(m[1])
	parts := strings.Split(m[2], ":")
	if len(parts) < 4 {
		return ""
	}
	host := pyStrip(parts[0])
	port := pyStrip(parts[1])
	username := pyStrip(parts[2])
	password := pyStrip(strings.Join(parts[3:], ":"))
	if host == "" || !pyIsDigit(port) || username == "" {
		return ""
	}
	if scheme == "socks5" {
		scheme = "socks5h"
	}
	return joinProxyURL(scheme, host+":"+port, username+":"+password)
}

// proxyURLFromColonParts ports _proxy_url_from_colon_parts (app.py:2360).
func proxyURLFromColonParts(text, defaultScheme string) string {
	if reAnySchemePrefix.MatchString(text) || strings.Contains(text, "@") {
		return ""
	}
	parts := strings.Split(text, ":")
	if len(parts) < 4 {
		return ""
	}
	host := pyStrip(parts[0])
	port := pyStrip(parts[1])
	if host == "" || !pyIsDigit(port) {
		return ""
	}
	username := pyStrip(parts[2])
	password := pyStrip(strings.Join(parts[3:], ":"))
	if username == "" {
		return ""
	}
	return joinProxyURL(defaultScheme, host+":"+port, username+":"+password)
}

// proxyURLFromSpaceParts ports _proxy_url_from_space_parts (app.py:2377).
func proxyURLFromSpaceParts(text, defaultScheme string) string {
	raw, err := shlexSplit(text)
	if err != nil {
		return ""
	}
	tokens := make([]string, 0, len(raw))
	for _, token := range raw {
		// Python filters on `token.strip()` being truthy but keeps the
		// quote-stripped value, which is itself stripped — not the same as
		// dropping strings.TrimSpace(token) == "".
		if pyStrip(token) == "" {
			continue
		}
		tokens = append(tokens, stripWrappingQuotes(token))
	}
	if len(tokens) == 0 {
		return ""
	}
	scheme := defaultScheme
	switch strings.ToLower(tokens[0]) {
	case "http", "https", "socks5", "socks5h":
		if strings.EqualFold(tokens[0], "socks5") {
			scheme = "socks5h"
		} else {
			scheme = strings.ToLower(tokens[0])
		}
		tokens = tokens[1:]
	}
	if len(tokens) == 2 && strings.Contains(tokens[0], ":") && strings.Contains(tokens[1], ":") {
		return joinProxyURL(scheme, tokens[0], tokens[1])
	}
	if len(tokens) >= 4 && pyIsDigit(tokens[1]) {
		return joinProxyURL(scheme, tokens[0]+":"+tokens[1], tokens[2]+":"+tokens[3])
	}
	return ""
}

// NormalizeProxyURL ports normalize_proxy_url (app.py:2396) with app.py's
// default_scheme="http".
func NormalizeProxyURL(value string) string {
	return NormalizeProxyURLWithScheme(value, "http")
}

// NormalizeProxyURLWithScheme is normalize_proxy_url with an explicit
// default_scheme (Go has no default arguments).
func NormalizeProxyURLWithScheme(value, defaultScheme string) string {
	text := cleanProxyInput(value)
	if text == "" {
		return ""
	}
	if curlProxy := proxyURLFromCurlCommand(text, defaultScheme); curlProxy != "" {
		return curlProxy
	}
	if schemeColonProxy := proxyURLFromSchemeColonParts(text); schemeColonProxy != "" {
		return schemeColonProxy
	}
	// Order matters: space parts are tried before colon parts, so
	// "host:port:user:pass" (a single shlex token) falls through to colon parts.
	if spaceProxy := proxyURLFromSpaceParts(text, defaultScheme); spaceProxy != "" {
		return spaceProxy
	}
	if colonProxy := proxyURLFromColonParts(text, defaultScheme); colonProxy != "" {
		return colonProxy
	}
	if reKnownSchemePrefix.MatchString(text) {
		if reSocks5Prefix.MatchString(text) {
			_, rest, _ := strings.Cut(text, "://")
			return "socks5h://" + rest
		}
		return text
	}
	if !strings.Contains(text, "://") {
		text = defaultScheme + "://" + text
	}
	// An unknown scheme (ftp://…) is returned verbatim, exactly as in Python.
	return text
}
